### ISSUE TITLE
Stadtbücherei Frankfurt

### ISSUE THREAD

**Issue by mswientek** [stefanw/bibbot#100]
**URL des Digitalangebots der Bibliothek**
https://frankfurt.de/service-und-rathaus/verwaltung/aemter-und-institutionen/stadtbuecherei/ebibliothek

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
Munzinger wird angeboten: https://frankfurt.de/service-und-rathaus/verwaltung/aemter-und-institutionen/stadtbuecherei/ebibliothek/munzinger-und-duden

**Comment by stefanw** [comment]
Momentan wird nur Genios ordentlich unterstützt.
