### ISSUE TITLE
VOEBB nervt mit neuem Einwilligungsfenster (Altersnachweis) - was derzeit ein showstopper für den BibBot ist. 

### ISSUE THREAD

**Issue by Wikinaut** [stefanw/bibbot#115]
![grafik](https://user-images.githubusercontent.com/1151915/164995497-66a1db52-cf25-49cc-bcb9-b3087e9c970b.png)

**Comment by Milszus** [comment]
Wirklich ätzend und ein Showstopper, weil das Login unterbrochen wird. 
Man könnte fast den Verdacht bekommen, das ist explizit gegen BibBot gerichtet…
