### ISSUE TITLE
Artikel später lesen Funtkion - Frage

### ISSUE THREAD

**Issue by gelsas** [stefanw/bibbot#117]
Hallo, ich nutze https://getpocket.com/de/ und speichere mir gerne Artikel ab um sie später zu lesen. 

Bei Paywall Artikeln klappt das leider nicht, daher meine Frage gibt es die Möglichkeit die "entsperrten" Artikel in Pocket zu speichern?

(Kenne mich nicht so sehr mit der technik aus, deswegen dachte ich das ich hier einfach mal Frage.)

LG

**Comment by stefanw** [comment]
Leider kann Pocket keine kompletten Inhalt speichern, sondern nur URLs aufrufen. Wenn Pocket die URL aufruft, dann ist der Inhalt aus der Bibliothek aber natürlich nicht da. Daher funktioniert Pocket leider so nicht.

In den Einstellungen gibt es unter "Weitere Einstellungen" eine "Artikel später lesen"-Funktion, die eine URL akzeptiert, an die der Artikelinhalt gesendet werden kann. Dies dient dafür eine Privatkopie anzulegen.
Als Beispiel-Software gibt es [ein Repo](https://github.com/stefanw/articles-to-feed), das eine kleine Datenbank beim Cloud-Provider fly.io anlegt, Inhalte über eine URL akzeptiert und diese dann als Atom-Feed zurückgibt. Die kann man dann mit einem Feed-Reader abonnieren und z.B. mobil lesen.
