### ISSUE TITLE
Exclude Seiten

### ISSUE THREAD

**Issue by andi1103** [stefanw/bibbot#121]
Hi,

Erstmal Danke für das Plugin!

Einen Feature Wunsch hätte ich: Es wäre gut, wenn man Seiten aus dem automatischen Aufruf rausnehmen könnte, damit nicht immer die genios Seite aufgeht. Ich habe ein Abo einer der Seiten.

Viele Grüße aus Dresden
AnDi

**Comment by BenutzerEinsZweiDrei** [comment]
Issue doppelt mit hier https://github.com/stefanw/bibbot/issues/39
