### ISSUE TITLE
Request: Safari Version

### ISSUE THREAD

**Issue by csteinlehner** [stefanw/bibbot#122]
Gibt es Pläne bzw. überhaupt die 'einfache' Möglichkeit dieses Plugin als Mac Safari Version herauszubringen?

**Comment by kesselborn** [comment]
https://developer.apple.com/forums/thread/94567

Es gibt ein Tool, um Extensions zu konvertieren. Ein schneller Test war erst mal vielversprechend: Preferences, etc. gingen, Tab wird im Hintergrund geöffnet, aber leider wird keine Suche bei Genios gestartet.

**Comment by stefanw** [comment]
[macOS Safari Extension](https://apps.apple.com/app/bibbot/id6443782967)

**Comment by iMonZ** [comment]
> Ich habe das mal gemacht und schon lokal getestet.
> 
> Hier ist eine TestFlight-Link für iOS (gültig noch 87 Tage): https://testflight.apple.com/join/lquHIgLN
> 
> Die macOS Safari-Version ist bald unterwegs.

Hey kannst du den bitte nochmal erneuerten?

**Comment by iMonZ** [comment]
> [macOS Safari Extension](https://apps.apple.com/app/bibbot/id6443782967)

Die App ist nicht in meinem Land verfügbar :(
In welchen Ländern ist die Extension verfügbar?
