### ISSUE TITLE
Stadtbibliothek Erlangen

### ISSUE THREAD

**Issue by mojoaxel** [stefanw/bibbot#13]
**URL des Digitalangebots der Bibliothek**
https://www.erlangen.de/bibliothek/

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**

- https://www.munzinger.de/search/login?portalid=50806

**Comment by stefanw** [comment]
Can you check what is actually provided via the library? Login with your account and check the left sidebar under "Presse".

**Comment by Nihlo** [comment]
https://github.com/stefanw/bibbot/issues/130

**Comment by mojoaxel** [comment]
Closing in favor of #130
