### ISSUE TITLE
Stadtbibliothek Nürnberg

### ISSUE THREAD

**Issue by WolfRevo** [stefanw/bibbot#137]
**URL des Digitalangebots der Bibliothek**
https://www.nuernberg.de/internet/stadtbibliothek/digitaleangebote.html

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
Genios: ja (siehe unten: https://bib-nuernberg.genios.de/)
Munzinger: ja (https://www.nuernberg.de/imperia/md/stadtbibliothek/dokumente/anleitung_pressreader_stb_2022.pdf)
NexisUni: nein

Danke im Voraus für deine Mühen und dein Engagement 😀

**Comment by imy1** [comment]
**Genios ist im Angebot.**
Genios: https://bib-nuernberg.genios.de/

**Comment by Nihlo** [comment]
wird nun unterstützt

**Comment by WolfRevo** [comment]
Vielen Dank, funktioniert 😊
