### ISSUE TITLE
Neue Bibliothek: rlp.onleihe.de

### ISSUE THREAD

**Issue by monora** [stefanw/bibbot#144]
**URL des Digitalangebots der Bibliothek**
https://rlp.onleihe.de

**Hat die Bibliothek Genios, Munzinger, Nexis Uni oder andere Pressedatenbanken im Angebot?**
Ja, zumindest mit Munzinger konnte ich mich anmelden. Bei Genios bin ich auf die Schnelle nicht fündig geworden.

**Comment by stefanw** [comment]
Leider geht Bibbot ohne die Pressedatenbank Genios nicht.
