### ISSUE TITLE
Stadtbücherei Frankfurt bitte hinzufügen

### ISSUE THREAD

**Issue by Baran4205** [stefanw/bibbot#145]
**URL des Digitalangebots der Bibliothek**
https://...

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**

**Comment by stefanw** [comment]
Leider geht Bibbot ohne Genios nicht, was offenbar nicht von der Stadtbücherei Frankfurt angeboten wird.
