### ISSUE TITLE
Zeitraum bei Wirtschaftswoche entfernen

### ISSUE THREAD

**Issue by pschopen** [stefanw/bibbot#152]
Die Artikel in der Wirtschaftswoche haben bei genios oft ein anderes Datum als auf der Website. Deshalb werden häufig Artikel nicht gefunden. Es würde sich vielleicht anbieten, die Zeitraum-Abfrage zu entfernen?

**Comment by stefanw** [comment]
Kannst du einen konkreten Heise-URL nennen? Die Layouts sind da manchmal unterschiedlich und offenbar funktioniert da die query extraktion nicht.

**Comment by Wever1985** [comment]
Sorry, dass ich das nochmal ausgrabe, aber das Problem besteht für heise.de weiterhin. Hier z.B. ein Artikel, der von Bibbot aufgrund des zu eng gesetzen Zeitfenster-Filters nicht entdeckt wird, aber auf Genios existiert: https://www.heise.de/ratgeber/BibBot-Browser-Add-on-zum-Lesen-hinter-vielen-Paywalls-10453174.html

(Filter: 23.06.2025 - 02.07.2025, Artikel auf Genios vom 11.07.2025)
