### ISSUE TITLE
Stadtbibliothek Köln nicht im Plugin, aber auf der Website

### ISSUE THREAD

**Issue by pattex** [stefanw/bibbot#154]
Hallo,

ich habe gerade festgestellt, dass die Stadtbibliothek Köln zwar auf https://stefanw.github.io/bibbot/ aufgeführt wird, im Plugin allerdings leider nicht zu finden ist.

Ansonsten: Eine tolle Idee und ein super Projekt. Danke!

Schöne Grüße
Arne

**Comment by stefanw** [comment]
Köln hat kein genios.de, sondern nexis-uni. Dafür ist jetzt beta-mäßig support da im nächsten Release, das in den kommenden Stunden hoffentlich live geht. Gerne Feedback dazu, habe nexis-uni nicht ganz durchschaut.

**Comment by pattex** [comment]
Hallo Stefan,
nach dem Update konnte ich die Stadtbibliothek Köln nun auswählen. Ich habe meine Zugangsdten eingetragen und dann den Test-Link (unten im Einstellungsbereich) geklickt.

Ich lande dann allerdings immer, ohne irgendeine Fehlermeldung o.Ä. an der Paywall von Zeit Online. Gibt es irgendein Log, in dem ich nachsehen kann, an welcher Stelle es möglicherweise hakt?

**Comment by stefanw** [comment]
Öffnet sich kein weiteres Tab mit nexis? Welchen Browser verwendest du? Möchte das Add-On irgendwo Berechtigungen für weitere Domains?

**Comment by pattex** [comment]
> Öffnet sich kein weiteres Tab mit nexis?
Es öffnet sich ausschließlich ein neues Tab mit der Zeit Online Pay-Wall, das war's.

> Welchen Browser verwendest du?
Ich verwende derzeit Firefox 106.0.5.

> Möchte das Add-On irgendwo Berechtigungen für weitere Domains?
Als ich die Einstellung gemacht habe, hat es mich nach der Berechtigung für eine Domain der Stadtbibliothek Köln gefragt, die ich erteilt habe.

**Comment by cdoppler** [comment]
Wurde die Unterstützung für die Stadtbibliothek Köln bzw. Nexis Uni im Allgemeinen eingestellt?

**Comment by pattex** [comment]
> Wurde die Unterstützung für die Stadtbibliothek Köln bzw. Nexis Uni im Allgemeinen eingestellt?

Das würde mich auch sehr interessieren. Es hat bisher bei mir leider nicht funktioniert.
