### ISSUE TITLE
Genios (Stadtbib Düsseldorf) findet keine Artikel - Unterstützung für PressReader?

### ISSUE THREAD

**Issue by mbelow** [stefanw/bibbot#155]
Ich finde die Idee klasse, mit der Umsetzung hatte ich aber bisher kein Glück: Bei Zeit, Spiegel und Süddeutsche finde ich keinen einzigen Artikel. Offenbar hat die Stadtbib Düsseldorf nur eine Sparversion von Genios. Dafür gibt es aber NexisUni und PressReader, könnte das evtl. unterstützt werden?

**Comment by ituri** [comment]
Habe das gleiche Problem mit der Stadtbibliothek Düsseldorf.

**Comment by stefanw** [comment]
Es fehlen mir Zugangsdaten, um das genauer zu Debuggen. Gerne vertraulich an meine E-Mail-Adresse.

**Comment by MarcusBlitz** [comment]
Ich habe bei Genios nachgefragt: "Die Stadtbibliothek Düsseldorf hat ihren Nutzungsvertrag für die GENIOS eBiB zum 31.12.2022 gekündigt. Daher ist kein Login auf der u.g. Seite möglich."
Sie nutzen jetzt onleihe - lässt sich das auch in BibBot integrieren?

**Comment by neufeind** [comment]
Für Artikel nutzen Sie PressReader.

URL des Digitalangebots der Bibliothek:
https://www.duesseldorf.de/stadtbuechereien/onlinebibliothek.html
