### ISSUE TITLE
Fernuni Hagen leitet nur auf manuelle Suche

### ISSUE THREAD

**Issue by BenutzerEinsZweiDrei** [stefanw/bibbot#158]
Über Fernuni Hagen ersetzt der Bibbot nicht den Artikel, sondern öffnet nur einen neuen Tab mit der manuellen Suche. Probiert mit Spiegel+ und Welt+

**Comment by BenutzerEinsZweiDrei** [comment]
Hallo ich denke hat zu tun mit diesem Issue

https://github.com/stefanw/bibbot/issues/151

**Comment by BenutzerEinsZweiDrei** [comment]
Close war versehentlich..

**Comment by stefanw** [comment]
Es fehlen mir Zugangsdaten, um das genauer zu debuggen. Gerne vertraulich an meine E-Mail-Adresse.

**Comment by BenutzerEinsZweiDrei** [comment]
Habe es grad am PC getestet. Auch hier funktioniert es nicht mit Fernuni Hagen.

**Comment by stefanw** [comment]
Ich habe es getestet und bei mir hat es mit dem Test-Artikel und Version 0.26 geklappt.

Wenn es nicht geht, bitte gebt an:
- Versionsnummer der Extension
- URL des Artikels
- Browsername und Version
