### ISSUE TITLE
Safari Extension für iPad

### ISSUE THREAD

**Issue by amz71** [stefanw/bibbot#161]
Wäre es möglich, die Safari-Extension auch für das iPad anzubieten? Safari auf dem iPad zeigt Extensions zum installieren an, BibBot ist leider nicht dabei. Merci.

**Comment by stefanw** [comment]
Leider wurde die Extension für den iOS AppStore vor kurzem abgelehnt.

**Comment by amz71** [comment]
Und was hat Apple als Begründung angegeben? Vielleicht lässt sich Widerspruch einlegen?

**Comment by stefanw** [comment]
Hatte auch schon Widerspruch eingelegt. Deren Standpunkt ist, dass die Extension Inhalte von Dritten anzeigt, es aber keine Verträge mit diesen Dritten gibt, die es aber nach deren Auffassung für den App Store bräuchte. Haben das Konzept der Bibliothek offenbar leider nicht verstanden.
