### ISSUE TITLE
Stadtbücherei Paderborn

### ISSUE THREAD

**Issue by Cassarah777** [stefanw/bibbot#164]
**URL des Digitalangebots der Bibliothek**
https://...

**Hat die Bibliothek die Pressedatenbank Genios im Angebot?**

Falls nicht, funktioniert die Erweiterung mit der Bibliothek leider nicht.
Falls ja, gib bitte die URL zu der Genios-Seite an:

**Comment by stefanw** [comment]
Die Bibliothek hat leider nur Munzinger, was gerade nicht richtig unterstützt wird.
