### ISSUE TITLE
Leo - Lesen Online Sued

### ISSUE THREAD

**Issue by Sendekomplex** [stefanw/bibbot#174]
**URL des Digitalangebots der Bibliothek**
https://leo-sued.onleihe.de/leo-sued/frontend/welcome,51-0-0-100-0-0-1-0-0-0-0.html

**Hat die Bibliothek die Pressedatenbank Genios im Angebot?**
Meines Wissens nicht, wäre aber wünschenswert, da das Lesen am Rechner mit ganzseitigem Zeitungsformat und ohne Suchmöglichkeit sehr anstrengend ist. Da verliert man mehr Zeit mit Suchen als Lesen innert der einen Stunde, in der man die Publikation ausleihen kann.
Falls nicht, funktioniert die Erweiterung mit der Bibliothek leider nicht.
Falls ja, gib bitte die URL zu der Genios-Seite an:

Vielleicht können Sie an den Bibliotheksverbund herantreten.

**Comment by stefanw** [comment]
Entschuldigung, aber das ist wirklich nicht meine Aufgabe. Wenn du dort Kunde bist, schreib denen doch gerne ein E-Mail. Sie scheinen ja ein Angebot auf Basis von PressReader zu haben. Momentan versuche ich zu eruieren, ob damit eine Integration möglich ist.
