### ISSUE TITLE
Cannot open articles with Leipziger Stadtbibliotheken

### ISSUE THREAD

**Issue by georgkrause** [stefanw/bibbot#176]
I am not exactly sure, how this happens, but I try to open an article. For example the example article from the settings: https://www.zeit.de/2021/11/soziale-ungleichheit-identitaetspolitik-diskriminierung-armut-bildung

A new tab gets opened, showing the GENIOS search mask, but nothing else happens.

When I debug the plugin, I get the following:

```
tab created 48 [background.js:2333:21](moz-extension://f65b3f56-99d5-45af-bfd5-5e07b090fb8b/build/background.js)
tab load complete 48 [background.js:2357:21](moz-extension://f65b3f56-99d5-45af-bfd5-5e07b090fb8b/build/background.js)
Uncaught (in promise) Error: Missing host permission for the tab undefined
    rejected moz-extension://f65b3f56-99d5-45af-bfd5-5e07b090fb8b/build/background.js:1300
    (Async: promise callback)
    step moz-extension://f65b3f56-99d5-45af-bfd5-5e07b090fb8b/build/background.js:1301
    __awaiter moz-extension://f65b3f56-99d5-45af-bfd5-5e07b090fb8b/build/background.js:1302
    __awaiter moz-extension://f65b3f56-99d5-45af-bfd5-5e07b090fb8b/build/background.js:1298
    runNextSourceStep moz-extension://f65b3f56-99d5-45af-bfd5-5e07b090fb8b/build/background.js:2362
    onTabUpdated moz-extension://f65b3f56-99d5-45af-bfd5-5e07b090fb8b/build/background.js:2358
    onTabUpdated self-hosted:1356
    apply self-hosted:2736
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:625
    fire resource://gre/modules/ExtensionChild.jsm:832
    recvRunListener resource://gre/modules/ExtensionChild.jsm:836
    recvRunListener self-hosted:1356
    _recv resource://gre/modules/ConduitsChild.jsm:82
    receiveMessage resource://gre/modules/ConduitsChild.jsm:188
```

Am I doing something wrong? Thanks for the great plugin!

**Comment by stefanw** [comment]
This sounds a bit like host permissions for a domain have not been granted. Could you check in your add-on settings for BibBot if there's a prompt for granting additional permissions? Alternatively try changing your library to a different one and back to see if a permission prompt comes up.

I've seen permission prompts acting funnily in the past. The problem is that some changed permissions can only be prompted on explicit user actions.

**Comment by leo-liar** [comment]
Unfortunately using Leipziger Städtische Bibliotheken hasn't been working for quite some time, e.g.:

- https://github.com/stefanw/bibbot/issues/85#issuecomment-1079911552
- #129 

Though I'm curious, maybe it's got something to do with host permissions or something like that.

**Comment by stefanw** [comment]
Unfortunately, I cannot find the error without a local library account. If someone is willing to confidentially share credentials (I promise to only use it for debugging), please find my email address.

**Comment by leo-liar** [comment]
I just gave it a try again yesterday, but the error still persists as described by me in the above-mentioned issues.

I will send you my credentials via email. User @dasinking (opened issue #129) also offered to provide their credentials.

**Comment by dasinking** [comment]
My offer for providing credentials is still available as well. :)
