### ISSUE TITLE
Bayerische Staatsbibliothek

### ISSUE THREAD

**Issue by abspann** [stefanw/bibbot#178]
**URL des Digitalangebots der Bibliothek**
https://www.bsb-muenchen.de/recherche-und-service/suchen-und-finden/

**Hat die Bibliothek die Pressedatenbank Genios im Angebot?**

Falls nicht, funktioniert die Erweiterung mit der Bibliothek leider nicht.
Falls ja, gib bitte die URL zu der Genios-Seite an:
Ja, http://emedia1.bsb-muenchen.de/han/wiso/ 
Nach dem Login: https://www-1wiso-2net-1de-1001394go0ffe.emedia1.bsb-muenchen.de/dosearch

**Comment by abspann** [comment]
Klappt mit meiner Kennung leider noch nicht. Getestet auf zeit.de und spiegel.de .
Ich sehe jeweils einen zusätzlichen Browsertab mit der wiso-Datenbank (die erst mal nach einem Login fragt). Aber auch nach Login sehe ich auf der Artikelseite nur den grünen Bibbot-Kasten "Pressedatenbank wird aufgerufen..."

**Comment by stefanw** [comment]
Ja, das mit dem Code klingt plausibel. Welche Seite muss man denn aufrufen, um auf diese Code-Domain zu kommen?

**Comment by abspann** [comment]
Zuerst muss ich mich auf https://login.emedia1.bsb-muenchen.de/loginuser/bsbLogin.html einloggen (diese Loginseite ist für alle Datenbankangebote der BSB gleich), danach lande ich dann auf der Code-Domain und muss dort dann noch die Nutzungsbedingungen bestätigen.

**Comment by NashVio** [comment]
Bin mir nicht sicher, ob ganz folgen kann, aber verstehe ich es richtig, dass es mit der Bayerischen Staatsbibliothek aktuell nicht funktioniert?

**Comment by abspann** [comment]
Nein, meines Wissens hat's bisher noch nie richtig funktioniert. Es gibt aber seit Anfang Mai eine Änderung beim Login-Prozess der BSB nach dem Aufruf von http://emedia1.bsb-muenchen.de/han/wiso/

Jetzt läuft es so ab:
1. Schritt: Frage nach Heimatinstitution (https://login.emedia1.bsb-muenchen.de/loginuser/bsbLogin.html)
2. Schritt: Neue Login-Seite https://idp.bsb-muenchen.de/idp/Authn/BSB?conversation=e1s1
3. Schritt: Angaben zur Informationsweitergabe (Ablehnen oder Akzeptieren)

Erst nach Akzeptieren in Schritt 3 gelangt man schließlich zur Wiso-Datenbank:
https://www-1wiso-2net-1de-101vwuxli0d4c.emedia1.bsb-muenchen.de/dosearch
wobei sich der 13-stellige Code wohl jedes Mal neu ausgewürfelt wird.

Vielleicht kann @stefanw ja nochmal schauen, ob sich das irgendwie in BibBot einbauen lässt. Wenn nicht, müsste die BSB aus der Liste der unterstützten Bibliotheksseiten entfernt werden.

**Comment by juleztb** [comment]
Die StaBi hat bei mir auf jeden Fall funktioniert, als ich mich im April extra deswegen dort angemeldet habe.
Leider war meine Anmeldung nur einen Monat gültig (reine Onlineanmeldung). Gestern habe ich mir dort den physischen Ausweis geholt und komme nun wieder rein. Aber jetzt funktioniert der BibBot nicht mehr mit dem von euch beschriebenen Problem. 

Der Code scheint aber nicht zufällig zu sein. Der aus deinem letzten Link @abspann funktioniert bei mir nämlich auch. Der aus den vorherigen nicht.
Es scheint mir so, als wären diese Links nicht komplett zufällig sondern immer eine längere Zeit gültig. Vllt einen Monat?
Irgendwie muss es ja bei mir im April auch funktioniert haben.

**Comment by bastigruenwald** [comment]
Ich bin jetzt auch frisch dabei und auch StaBi-Kunde. Das Problem scheint noch zu bestehen: Es öffnet der falsche Wiso-Link und der BitBot kann sich nicht einloggen.

Wäre es nicht denkbar, den richtigen "dynamischen" Link aus der http://emedia1.bsb-muenchen.de/han/wiso/ zu generieren? Der leitet doch immer dann auf den jeweils dynamischen weiter.

**Comment by lennarto** [comment]
Ist diese Änderung schon in der Version 0.39.2 drin? :) Bei mir klappt es leider immer noch nicht :(
