### ISSUE TITLE
Stadtbibliothek Winnenden canceled their Genios access

### ISSUE THREAD

**Issue by FroehlichMarcel** [stefanw/bibbot#179]
It seems that the library received a one-year grant in 2022 from the state used to pay for GENIOS access.
With the funding gone, they immediately canceled the subscription.
Just wanted to set up bibbot and was stopped on the GENIOS login page.
How much functionality is left via Munzinger (given the login attempt is removed)?

**Comment by stefanw** [comment]
Depends on their contract with Munzinger, but right now Munzinger is not really tested. I'm looking into Pressreader integration.

**Comment by FroehlichMarcel** [comment]
> Depends on their contract with Munzinger, but right now Munzinger is not really tested. I'm looking into Pressreader integration.

Cool, Pressreader works, but searching for news directly in Munzinger seems not to work.

Thanks!
