### ISSUE TITLE
Tabs werden geschlossen

### ISSUE THREAD

**Issue by kenknoll** [stefanw/bibbot#183]
Schritte:
1. Öffnen eines neuen S+-Artikels
2. Tab zu genios geht auf
3. Artikel wird gefunden
4. Tab wird wieder automatisch geschlossen

Erwartetes Verhalten: Tab nicht schließen :)

Danke!

**Comment by stefanw** [comment]
Der Text des Artikels sollte in den Original-Artikel eingefügt werden, wenn der Artikel gefunden wird. Sollte der Artikel-Text nicht eingefügt werden, ist das ein Bug. Nach dem Einfügen wird das Tab zu genios geschlossen. `Cmd+Shift+T` oder eine Entsprechung kann das geschlossene Tag auch wieder herstellen. Das Tab bleibt nur offen, wenn der Artikel nicht gefunden werden kann.
