### ISSUE TITLE
Support for Stadtbibliothek München (https://www.muenchner-stadtbibliothek.de/digitale-angebote)

### ISSUE THREAD

**Issue by ghac101** [stefanw/bibbot#186]
**URL der Nachrichtenseite**
https://...

**URL zu einem Artikel mit Paywall**
https://...

**Ist die Nachrichtenseite bei Genios enthalten?**
Bitte bei Genios unter Quellen -> Alle Quellen prüfen.

**Comment by mo7211** [comment]
**URL des Digitalangebots der Bibliothek**
https://www.muenchner-stadtbibliothek.de/

**Hat die Bibliothek eine Pressedatenbank wie Genios oder LexisNexis im Angebot?**

Falls nicht, funktioniert die Erweiterung mit der Bibliothek leider nicht. 
Falls ja, gib bitte die URL zu der Pressedatenbank an:
"Diese Datenbank können Sie vor Ort in Ihrer Stadtbibliothek nutzen." Reicht das aus?

**Comment by darkdragon-001** [comment]
Duplicate of #110

**Comment by Strubbl** [comment]
Wenn LexisNexis nur vor Ort geht, denke ich nicht, dass sich das mit diesem Plugin verwirklichen lässt.
