### ISSUE TITLE
Pls add the "stadtbibliothek Göttingen" to the list.

### ISSUE THREAD

**Issue by Grawy82** [stefanw/bibbot#192]
**URL des Digitalangebots der Bibliothek**
https://www.onleihe.de/goettingen/frontend/myBib,6465-0-0-100-0-0-0-0-0-0-0.html

**Hat die Bibliothek die Pressedatenbank Genios im Angebot?**

Falls nicht, funktioniert die Erweiterung mit der Bibliothek leider nicht.
Falls ja, gib bitte die URL zu der Genios-Seite an:

**Comment by stefanw** [comment]
Momentan nicht kompatibel.
