### ISSUE TITLE
Funktioniert bei mir gar nicht

### ISSUE THREAD

**Issue by Alucard712** [stefanw/bibbot#195]
Getestet mit Spiegel Online, Zeit und dem Test-Artikel aus den Addon-Settings unter Windows 10 und Firefox 110.0.1 und Chrome  111.0.5563.65.

Bei mir wird nur die animierte Meldung angezeigt "Pressedatenbank wird aufgerufen..." - mehr passiert nicht. Was mache ich falsch?

Mein Genios-Login über die Stadtbibliothek Darmstadt funktioniert und via manueller Suche werden die Artikel auch gefunden - daran kann es schonmal nicht liegen. Aktivieren und Deaktivieren von Adblockern o.ä. hat auch keinen Einfluss.

**Comment by stefanw** [comment]
Ggf. keine Bibliotheks-Zugangsdaten angegeben? Dafür sollte es wohl eine echte Fehlermeldung geben.

**Comment by stefanw** [comment]
Ansonsten bitte mal in die Developer Tools unter Console nach Fehlermeldungen von BibBot gucken.

**Comment by Alucard712** [comment]
Moins. Erstmal danke für die zeitnahe Antwort :-)

> Ggf. keine Bibliotheks-Zugangsdaten angegeben? Dafür sollte es wohl eine echte Fehlermeldung geben.

Zugangsdaten sind angegeben und korrekt. Allerdings habe ich festgestellt, dass der Login nicht über einen Neustart des Browsers aufrecht gehalten wird (zumindest nicht im FF, der meine Hauptbrowser ist). Das scheint aber mir eine Macke der Genios-Seite zu sein, die den Login immer wieder erneuert haben will o.O

> Ansonsten bitte mal in die Developer Tools unter Console nach Fehlermeldungen von BibBot gucken.

Hier kann/konnte ich nichts finden. Der Fehler ist mittlerweile (zumindest für den Moment) auch verschwunden: Cookies zu löschen und andere FF-Addons zu deaktivieren und wieder zu reaktivieren, hat die Sache irgendwie zum Laufen gebracht. Was da jetzt nicht funktioniert hat und warum nicht, lässt sich so leider nicht mehr nachvollziehen.
