### ISSUE TITLE
Vorschläge

### ISSUE THREAD

**Issue by andreaseu** [stefanw/bibbot#201]
**URL der Nachrichtenseite**
https://https://www.lkz.de

**URL zu einem Artikel mit Paywall**
https://https://www.lkz.de/sport/basketball_artikel,-fanliebling-jaleen-smith-tut-seinem-ex-club-mhp-riesen-ludwigsburg-weh-_arid,727380.html](https://www.lkz.de/sport/basketball_artikel,-fanliebling-jaleen-smith-tut-seinem-ex-club-mhp-riesen-ludwigsburg-weh-_arid,727380.html

**Ist die Nachrichtenseite bei Genios enthalten?**
Bitte bei Genios unter Quellen -> Alle Quellen prüfen.

**Comment by fjd** [comment]
Ich konnte die Ludwigsburger Kreiszeitung (LKZ) in keinem System finden.

**Comment by stefanw** [comment]
Offenbar nicht vorhanden.
