### ISSUE TITLE
Bibbot hat aufgehört zu funktionieren

### ISSUE THREAD

**Issue by 343max** [stefanw/bibbot#207]
Seit einer weil geht die Bibot Erweiterung nicht mehr: die Erweiterung zeigt keinerlei Aktivität mehr. Es funktioniert auch mit dem Beispielartikel in den Einstellungen mehr.

Getestet mit: Firefox Extension in Firefox 112.0
Chrome Extension in Arc 0.97

**Comment by baurmatt** [comment]
Bei mir ebenfalls. Getestet mit https://www.zeit.de/2021/11/soziale-ungleichheit-identitaetspolitik-diskriminierung-armut-bildung

Firefox 111.0.1 mit Bibbot 0.25.6

**Comment by stefanw** [comment]
Zeit hatte seine Paywall-Struktur geändert, Version 0.26.0 sollte wieder gehen.

Bitte immer eine Bibliothek und eine URL eines Artikels angeben.
