### ISSUE TITLE
Stadtbibliothek Köln

### ISSUE THREAD

**Issue by Luki3004** [stefanw/bibbot#210]
Hallo zusammen, 

ich hoffe ich bin hier an der richtigen Stelle mit meinem Anliegen. 
Ich bin seit heute stolzes Mitglied der Stadtbibliothek Köln.
Laut der Github Hauptseite dieser Erweiterung gehört die Kölner Bis zu den unterstützten Bibliotheken. (https://stefanw.github.io/bibbot/) 
Ich habe die Erweiterung in safari installiert, in dem Einstellungsfenster in Safari ist die Kölner Bis aber nicht aufgeführt. Weder in der Liste der unterstützten Bibliotheken, noch weiter unten im DropDown Feld für die Anmeldung.

Ist das so beabsichtigt, wo liegt das Problem, lässt sich das lösen oder bin ich einfach blind? :D

Sollte das Problem bekannt sein oder ich hier mit meinem Anliegen falsch sein bitte ich um Verzeihung und Tipps, an wen ich mich wenden könnte.

Viele Grüße,
Lukas 

Als Anhang zwei Screenshots.

<details>

Auf der Startseite/Hauptseite/Website der Erweiterung:
<img width="1439" alt="Bildschirm­foto 2023-04-14 um 21 43 01" src="https://user-images.githubusercontent.com/130794636/232141547-5d0b018b-c8b3-4532-ba43-feb48aa8646e.png">

Auf der Seite der Einstellungen der installierten Erweiterung in Safari:
<img width="1440" alt="Bildschirm­foto 2023-04-14 um 21 47 38" src="https://user-images.githubusercontent.com/130794636/232141555-a4de4bb2-166e-4fd6-a0e4-6758db0b7e99.png">
</details>

**Comment by FlyingPersian** [comment]
Also ich kanns finden:

![Screenshot_20230414_220553_Kiwi Browser](https://user-images.githubusercontent.com/8209643/232144881-1666cdbf-518d-4d37-86e5-fbf0baeb3970.jpg)

**Comment by stefanw** [comment]
Der Release-Prozess für Safari ist komplizierter, muss über den App Store approved werden. Aktuelle Version ist 0.26, dort ist aber nur 0.23. Ein Update kommt. Allerdings ist die Stadtbibliothek Köln auch ein Sonderfall, weil dort nur LexisNexis angeboten wird, was momentan nur als beta getestet werden kann.
