### ISSUE TITLE
ZON: 'Beim Extrahieren der Artikeldaten trat ein Fehler auf'. (Firefox)

### ISSUE THREAD

**Issue by me3e3e** [stefanw/bibbot#218]
Ist o.g. Fehlermeldung bekannt?
Womit könnte es in Zusammenhang stehen?
Kann ich noch weitere Infos zur Verfügung stellen?
Danke!

**Comment by stefanw** [comment]
Danke für's debuggen!

**Comment by me3e3e** [comment]
Vielen Dank - das tut's!
