### ISSUE TITLE
Addon für Firefox: Beim Extrahieren der Artikeldaten trat ein Fehler auf

### ISSUE THREAD

**Issue by RichardBeisser** [stefanw/bibbot#221]
Hallo,

ich würde gerne BibBot im (aktuellen) Firefox nutzen.
Meinen Bibliothekszugang habe ich eingetragen. Wenn ich den Testartikel aufrufe, erhalte ich die Meldung

BibBot
Beim Extrahieren der Artikeldaten trat ein Fehler auf.

Ich habe zunächst alle anderen Addons deaktiviert um diese als Fehlerquelle auszuschließen.
Leider ohne Erfolg.

Warum wirft das Addon diesen Fehler?
Was kann ich tun?

Vielen Dank.

**Comment by stefanw** [comment]
Welche BibBot-Version? 0.26.5 ist gerade die aktuelle.

**Comment by RichardBeisser** [comment]
Hallo Stefan,
du hast recht.
Mein Firefox hat erst gerade das neuere Addon von addons.mozilla.org heruntergeladen welches du bei github schon vor 2 Tagen online gestellt hast.
Sorry, mein Fehler.
Mit dem aktualisierten Addons scheint's wieder zu funktionieren.
