### ISSUE TITLE
Unterschiede der Bibliotheken bei genios, Berechtigungsanfragen Firefox-Addon

### ISSUE THREAD

**Issue by RichardBeisser** [stefanw/bibbot#222]
Hallo Stefan,

nur 2 Fragen:

- Unterscheiden sich die Inhalte, auf die man bei genios zugreifen kann, je nach Bibliothek? Können die Bibliotheken quasi unterschiedlichen Content-Zugang bei genios einkaufen?
Ich frage weil mir aufgefallen ist dass im Browser auf der eingeloggten genios-Seite über dem Suchfeld steht "Suche in HB,HBON,HBGM,HBLI,HBMA,HBMB,HBZ"

- Das Firefox-Addon fragt manchmal nach neuen Berechtigungen, und zwar für einige Login-Domains für den Bibliothekszugang, und für einige Seiten der Zeitungen/Magazine.
Hat das seine Richtigkeit dass hier nur nach ein paar Adressen gefragt wird und nicht nach allen unterstützten Zugängen und Zeitungen/Magazinen?

Ich dachte ich stell die Fragen mal hier als Issue weil das andere Nutzer auch interessieren könnte.

Vielen Dank.

**Comment by stefanw** [comment]
1) So viel ich weiß ja, Berlin scheint z.B. keine FAZ zu haben. Die Suche listet alle Quellen auf. Manche Webseiten veröffentlichen Artikel aus mehreren Quellen.
2) Der Browser fragt nur nach neuen Berechtigungen, nach einem Update meist nur nach neu unterstützten Nachrichtenseiten. Beim Wählen der Bibliothek, werden die Berechtigungen für die gewählte Bibliothek erbeten.

Ich habe Discussions aktiviert, da passen Fragen besser als in Issues: https://github.com/stefanw/bibbot/discussions
