### ISSUE TITLE
heise.de

### ISSUE THREAD

**Issue by RichardBeisser** [stefanw/bibbot#228]
Hallo,

das Addon 0.26.5 für Firefox erkennt zwar die Plus-Seiten auf heise.de, scheint aber keinen Suchtext in das Suchfeld auf genios zu schreiben

Beispiellink:
https://www.heise.de/hintergrund/Leitfaden-Wie-Sie-kleine-und-grosse-Balkonkraftwerke-bauen-8923627.html

Ich würde mich über einen Fix freuen.

Vielen Dank

**Comment by seeba8** [comment]
Ich habe ein bisschen im Code herumgewühlt. In [sites.ts, Zeile 5](https://github.com/stefanw/bibbot/blob/9dab6d1048fb8eee148d43adb8b1c53ae84b6ce4/src/sites.ts#LL5C70-L5C70) von `node.innerText` auf `node.textContent` zu wechseln löst dieses Problem für Heise. Allerdings habe ich keine der anderen Seiten getestet, die `extractQuery` benutzen, daher kein pull request von mir. Ich bin mir der Auswirkungen nicht sicher. `innerText` gibt nur den sichtbaren Text zurück (bei heise ist das ein leerer String), während `textContent` sämtlichen Text zurückgibt ([Quelle](https://stackoverflow.com/questions/35213147/difference-between-textcontent-vs-innertext)).

**Comment by RichardBeisser** [comment]
ich habe bei bei genios angefragt und die Auskunft bekommen dass keine Bibliothek über Genios FAZ oder heise anbieten würde.
Daher bin ich verwundert weil heise.de in der Liste der unterstützten Nachrichtenseiten auftaucht.
Hast du einen Bibliothekszugang der heise-Artikel über genios anzeigt?

**Comment by seeba8** [comment]
Jein. Ich bin bei der Vöbb. Dort werden diverse Heise-Magazine unterstützt ([Beispiel](https://www.heise.de/ratgeber/Containerverpacker-Kubernetes-Anwendungen-mit-Helm-paketieren-8976672.html)):
![image](https://github.com/stefanw/bibbot/assets/8963663/4b74dd92-bd29-4cd9-9d41-ad18c11f7528)

Heise+ nicht, soweit ich das sehen kann. FAZ auch nicht.

**Comment by RichardBeisser** [comment]
was gibt es bei heise ausser heise+ noch für das man regulär bezahlen müsste?
Kannst du ein Beispiel nennen?

**Comment by seeba8** [comment]
Zur initialen Frage: Ich weiß nicht, wie das Venn-Diagramm zwischen Heise+ und Artikeln aus den diversen Magazinen (c't, iX, etc.) aussieht: Gibt es Heise+-Artikel, die nicht aus einem der Magazine kommen? Gibt es Magazin-Artikel, die nicht Heise+ sind? Mein aktueller Verdacht ist, dass die Vöbb einige Heise-Magazine (in dem Fall aus dem Screenshot offensichtlich c't) anbietet.

Zu Edit2: Der relevante URL-Parameter scheint `dbShortcut=MACI%2CTERE%2CCT%2CCTFO%2CIX%2CMAKE` zu sein. In der Quellenliste finde ich die entsprechenden Magazine nur via Beschreibungsfeld:
![image](https://github.com/stefanw/bibbot/assets/8963663/c6ee5be4-ca50-446c-b109-384e32de6e68)

**Comment by RichardBeisser** [comment]
über meine Bibliothek (Darmstadt) finde ich die heise-Magazine so nicht.
In dem Menü auf der linken Seite habe ich nur "Presse" und "Wirtschaft kompakt".

Könntest du mir auflisten was bei dir für Magazine/Zeitungen unter
- Fachpresse
- Publikumspresse
aufgelistet sind?

Vielen Dank.

**Comment by seeba8** [comment]
Ich weiß nicht, ob ich die ganze Liste hier posten darf. Unter Fachpresse hat der VÖBB 946 Einträge, unter Anderem "Die Tabak Zeitung", "PC Welt Online", "manager magazin", die obigen Heise-Zeitschriften, das Handelsblatt, und diverse Journale. 
Publikumspresse (93 Einträge) enthält Titel wie die Bunte, Geo, Gala, Neon, Rolling Stone.

Wenn du weitere Details möchtest, kann ich dir gerne die Listen exportieren und emailen.

Alternativ: Ein Bibliotheksabo in Berlin ist ziemlich günstig. Man muss allerdings bei der Registrierung eine Berliner Adresse angeben.

**Comment by RichardBeisser** [comment]
Danke, das von dir genannte reicht mir soweit mal um zu erahnen was sich hinter den zwei Menüpunkten verbirgt.
heise.de zählt übrigens auch zu "Fachpresse" hat mir genios mitgeteilt. Daher findest du die Magazine in der Suche und ich nicht.

Ich werde mal auf meine Bibliothek zugehen und fragen ob sie die beiden Module bei genios noch buchen würden.
Dass die VÖBB mit den 10Euro ein sehr günstiges Angebot hat kenne ich, und auch dass man sich nur mit Berliner Adresse registrieren kann.
2 Fragen dazu: verschicken die VÖBB etwas per Briefpost? Kann man nachträglich im Onlinebereich seine Adressdaten ändern auf etwas ausserhalb von Berlin?

**Comment by DKlemann** [comment]
Hi Richard,

> verschicken die VÖBB etwas per Briefpost?

Bei mir kam bislang nichts an.

> Kann man nachträglich im Onlinebereich seine Adressdaten ändern auf etwas ausserhalb von Berlin?

Vermutlich nicht, habe es aber nicht ausprobiert.
Übrigens funktioniert nicht nur Berlin selbst, sondern auch das Berliner Umland.

**Comment by SirUnreal** [comment]
Funktionieren Heise+ und/oder Heise-Magazine denn nun über VÖBB? In deren Suche finde ich zwar den einen oder anderen Artikel, ob bisher nicht einen aktuellen.

**Comment by mrtnmueller** [comment]
> Funktionieren Heise+ und/oder Heise-Magazine denn nun über VÖBB? In deren Suche finde ich zwar den einen oder anderen Artikel, ob bisher nicht einen aktuellen.

würde mich auch sehr interessieren

**Comment by SirUnreal** [comment]
Vermutlich nicht. Heise ist nirgends lesbar, auch gängige Möglichkeiten über Bypass Paywall Clean, archive.today, archive.ph usw. funzen alle nicht.
