### ISSUE TITLE
Falsche Artikel aus GENIOS für abendblatt.de

### ISSUE THREAD

**Issue by SimSon2710** [stefanw/bibbot#237]
Moin,

wenn ich den BibBot für Plus-Artikel des Hamburger Abendblatts verwende, zieht er zwar vermeintlich wie gewünscht einen Artikel des Hamburger Abendblattes aus der GENIOS-Datenbank, jedoch handelt es sich bei den Stichproben, die ich bisher genommen habe, nie um den richtigen Artikel. Konkret lässt sich das z. B. mit folgendem Artikel nachvollziehen:  https://www.abendblatt.de/hamburg/article238356887/Mit-Google-soll-Verkehr-in-Hamburg-besser-fliessen.html. Der HTML-Insert von BibBot findet jedoch mit diesem Artikel statt: https://buecherhallen.genios.de/document/HA__b475f67b264a597446f95d882805ccd55c173b35.

Hier noch ein Screenshot des Resultats:
![grafik](https://github.com/stefanw/bibbot/assets/82225296/ce498f73-789e-4f35-a2db-b4d1a2f63666)

Vielen Dank für dieses wundervolle Tool und beste Grüße!

**Comment by Titule1** [comment]
Passiert mir auch oft.
[https://www.zeit.de/campus/2023-09/wohnungsmarkt-vermieter-eigentum-erfahrungsbericht]
Die Überschrift und der Artikel passen nicht zusammen.
