### ISSUE TITLE
Unterstützung für Firefox Android oder als Userscript

### ISSUE THREAD

**Issue by Sommerwiesel** [stefanw/bibbot#246]
Hey,
ich würde gerne eine Version für Android sehen, ich denke die meisten lesen heutzutage Nachrichten auf dem Smartphone.
Alternativ wäre ein Userscript auch toll.

Wie siehts damit aus?

**Comment by PhilippBlue** [comment]
Ja bitte Unterstützung für Firefox Android. Dann könnte man auch unterwegs in den Öffis (wo ich am meisten Nachrichten lese) informiert sein. :) Vorallem, da ich auch nie am PC Zeitungen lese, nur mobil.

**Comment by BenutzerEinsZweiDrei** [comment]
Siehe

https://github.com/stefanw/bibbot/issues/151

Und

https://github.com/stefanw/bibbot/issues/22
