### ISSUE TITLE
Stadtbibliothek München

### ISSUE THREAD

**Issue by Rudolfkern** [stefanw/bibbot#250]
**URL des Digitalangebots der Bibliothek**
https://www.onleihe.de/muenchen/frontend/welcome,0-0-0-101-0-0-0-0-0-0-0.html

**Hat die Bibliothek eine Pressedatenbank wie Genios oder LexisNexis im Angebot?**

Falls nicht, funktioniert die Erweiterung mit der Bibliothek leider nicht. 
Falls ja, gib bitte die URL zu der Pressedatenbank an:

**Comment by darkdragon-001** [comment]
Duplicate of #186.
