### ISSUE TITLE
Stadt- und Landesbibliothek Dortmund

### ISSUE THREAD

**Issue by Ahoybrause** [stefanw/bibbot#262]
**URL des Digitalangebots der Bibliothek**
https://stlb-dortmund.digibib.net/search/eds

**Hat die Bibliothek eine Pressedatenbank wie Genios oder LexisNexis im Angebot?**

Falls nicht, funktioniert die Erweiterung mit der Bibliothek leider nicht. 
Falls ja, gib bitte die URL zu der Pressedatenbank an:

https://go.openathens.net/redirector/dortmund.de?url=http://www.nexisuni.com+

**Comment by Ahoybrause** [comment]
@stefanw there is a pull request for this. If login data is required, I will send it to you by email.

**Comment by stefanw** [comment]
I pushed a new version that includes Dortmund, but it's untested. If it doesn't work, credentials would help to debug!

**Comment by Ahoybrause** [comment]
Thank you very much for adding it @stefanw !

Unfortunately, the bot does not work properly for Dortmund.
A debug is necessary.
Credentials will be sent by email.
