### ISSUE TITLE
Keine Artikel mit Stadtbibliothek Aachen / Nexis Uni

### ISSUE THREAD

**Issue by freddiN** [stefanw/bibbot#267]
Laut Tab scheint das über Nexis Uni zu gehen, aber funktional sind bei mir keine Seiten (30+ Artikel getestet). Getestet habe ich heise, spiegel, zeit, rp-online, tagesspiegel und einige andere.

Ich glaube fast, ich habe da ein generelles Problem. Beisp:
https://www.spiegel.de/ausland/so-schwaecht-wladimir-putins-krieg-den-kampf-gegen-das-klima-a-19305d7c-c666-4e2f-9a0c-50ccda7181dd

Ich sehe "BibBot Pressedatenbank wird aufgerufen", aber nichts passiert. Ein Nexis Uni Tab ist geöffnet, aber es findet keine Suche statt.
Copy und paste ich "So schwächt Putins Krieg den Kampf gegen den Klimawandel" in die SUchzeile des Tabs, finde ich den Artikel und kann ihn dort lesen.

Für den Fall dass das ein lokales Problem ist: Hat jemand stand jetzt (16.6. 14:55) ein funktionierendes Beispiel über eine Bib, die ebenfalls Nexis Uni benutzt?

Chrome 114.0.5735.134, BibBot v0.26.7

**Comment by stefanw** [comment]
Stadtbibliothek Köln nutzt NexisUni, damit ist das getestet. Für Aachen kann ich es ohne Login-Daten leider nicht debuggen.

**Comment by freddiN** [comment]
Interessant, danke für die schhnelle Antwort.

Ich hab eine Mail mit meinen Zugangsdaten gesendet.

**Comment by stefanw** [comment]
Noch als Hinweis: Für NexisUni ist gerade kein Filter auf Nachrichtenquellen eingebaut. Ich freue mich auf Erfahrungsberichte aus der Praxis.

**Comment by stefanw** [comment]
Achja: nach dem Aktualisiert einmal in den Einstellungen zu einer anderen Bib und zurück wechseln, dann erst werden die notwendige Permissions abgefragt.

**Comment by freddiN** [comment]
Ich hab mir die 0.26.8 via zip installiert und getestet:
Spiegel läuft wunderbar, zeit.de ebenfalls.

Heise.de läuft tatsächlich ohne BibBot besser:

Vorher
![image](https://github.com/stefanw/bibbot/assets/14030572/b872756b-ad9a-4d81-b7cb-118d16ed186e)

Nachher:
![image](https://github.com/stefanw/bibbot/assets/14030572/d6b7f4f2-d699-42af-8eb5-c6dc97fa8660)

Das liegt scheinbar daran, dass der Artikel in Nexis Uni gekürzt ist:
![image](https://github.com/stefanw/bibbot/assets/14030572/5a4fef28-4a42-40be-8e44-b048a97adfd1)

Hier fällt mir lediglich der Vorschlag ein, eine Mindesttextlänge konfigurieren zu können, ab der ersetzt wird ...

Tagesspiegel findet bei mir nichts, die Artikel sind aber vorhanden. Beispiel:
https://www.tagesspiegel.de/wirtschaft/mobilitaet/verkehrsminister-wissing-im-interview-von-flachendeckend-tempo-30-halte-ich-nichts-9696884.html

![image](https://github.com/stefanw/bibbot/assets/14030572/5f2013e0-d56d-4073-92f6-15342605e88f)

Ich habe mein Passwort gerade wieder auf das in der Mail konfigurierte geändert, was gerne zum testen genutzt werden kann.

**Comment by freddiN** [comment]
Dasselbe Verhalten wie bei heise auch bei mopo.de, Beispiel:
https://www.mopo.de/hamburg/schluss-mit-tuetensuppen-ernaehrungs-offensive-an-hamburgs-grundschulen/

Vorher:
![image](https://github.com/stefanw/bibbot/assets/14030572/64d96053-dd17-4c43-8cce-7374af633c73)

Nachher:
![image](https://github.com/stefanw/bibbot/assets/14030572/7bdaa4ab-1f3b-4a35-87e7-e99f5c380082)

Nexis Uni:
![image](https://github.com/stefanw/bibbot/assets/14030572/e548d4b1-1927-46a1-97b6-bba3b0889a0f)
