### ISSUE TITLE
Add-On name change

### ISSUE THREAD

**Issue by stefanw** [stefanw/bibbot#29]
The add-on is currently called VÖBBot – named after VÖBB (Verbund öffentlicher Bibliotheken Berlins). I found the name VÖBB funny – a typical German acronym.

However, as of recently this add-on support more libraries and should reflect that in its name.

I'm currently thinking `BibBot`, but I'm open to suggestions.

**Comment by x86dev** [comment]
ÖBIBot (Öffentliche Bibliotheken Bot) perhaps? Just my 2c. Great work BTW :)

**Comment by errotu** [comment]
Ich mag `BibBot`. Verständlich und einprägsam. Man könnte auf der Webseite den (dienenden) Bot-Charakter auch noch stärker herausstellen (die Paywall wird nicht "umgangen", sondern der Bot serviert einem den Inhalt nur auf den Teller, den man gerade vor sich hat).
