### ISSUE TITLE
Suche startet nicht

### ISSUE THREAD

**Issue by Titule1** [stefanw/bibbot#298]
Nachdem ein Paywall-Artikel geöffnet wird, startet bibbot die Suche, es öffnet sich ein neues Fenster in dem Login-Daten abgefragt werden, danach ein Suchfenster mit den Resultaten.

Wenn ich das nächste mal einen Paywall-Artikel öffne, steht lediglich im Text "Bibbot Pressedatenbank wird aufgerufen" und das Symbol läuft hin und her. Weiter passiert nichts.

Nach Neustart des Browsers funktioniert es wieder.. ein Mal.

Windows 11
Firefox 116.0.1 (64-Bit)
BibBot v0.27.0

**Comment by tm1964** [comment]
Das kann ich genau so bestätigen!

MAC OSX Ventura 13.5
Firefox 115 und 116.02
BibBot v0.27.0

**Comment by stefanw** [comment]
Bei welchem Artikel denn? Oder welchem Medium?

**Comment by Titule1** [comment]
Immer.

Zeit.de, Spiegel.de, Heise.de

Es geht immer nur der erste Artikel. Danach muss man das add-on de-aktivieren und wieder aktivieren

**Comment by Maik-Wi** [comment]
Bei mir klappt es mit heise.de gerade auch nicht. zeit.de und spiegel.de funktionieren problemlos. 

- macOS 14.2.1
- Firefox 112.0
- Chrome 112.0.5615.137
- BibBot v0.34.0

Hier auch mal die URLs mit den ich getestet habe. 

- https://www.heise.de/ratgeber/Python-Mausbewegungen-und-Tastatureingaben-automatisieren-mit-PyAutoGUI-9594806.html
- https://www.heise.de/ratgeber/Den-Autofokus-spiegeloser-Kameras-meistern-9578176.html
- https://www.heise.de/tests/Drei-Monate-im-Praxistest-Das-bringt-ein-Heizungsluefter-wirklich-9602817.html

**Comment by LorenzBung** [comment]
Habe dasselbe Problem. Getestet mit spiegel.de, zeit.de, badische-zeitung.de
- Debian 12 stable
- Firefox 115.8.0esr
- BibBot v0.35.0

**Comment by Titule1** [comment]
Mittlerweile öffnet sich bei spiegel.de und heise.de nicht mal mehr die suchseite.
Es ist, als ob bibbot gar nicht installiert wäre.
Auf zeit.de funktioniert es noch (findet aber nichts... :/  )

**Comment by stefanw** [comment]
v0.39.2 ist die neueste Version. Ggf. Müssen credentials neu hinterlegt werden, da es ein Upgrade auf Manifest v3 ist. Firefox Add-On ist schon im store, chrome hängt noch in review.

**Comment by Titule1** [comment]
Danke, geht jetzt
