### ISSUE TITLE
heise+

### ISSUE THREAD

**Issue by niwi-hh** [stefanw/bibbot#30]
**URL der Nachrichtenseite**
https://www.heise.de/plus/

**URL zu einem Artikel mit Paywall**
https://www.heise.de/hintergrund/Grundwissen-Heimnetzverkabelung-Von-Notloesung-bis-professionell-4982195.html?wt_mc=intern.red.plus.topteaser.plus_index.teaser.teaser

**Ist die Nachrichtenseite bei Genios enthalten?**
Ja. Getestet über das Angebot der Bücherhallen Hamburg. Genios enthält alle periodisch von Heise herausgegebenen Magazine:
- c't Digitale Fotografie
- c't - magazin für computertechnik
- iX - Magazin für prof. Informatik
- Mac & I
- Make
- Technology Review

**Comment by stefanw** [comment]
Das ist bei meiner Bibliothek leider nicht dabei, habe es aber mal hinzugefügt.

Ggf. brauchen wir Abo include/exclude-Listen für Bibs.

**Comment by niwi-hh** [comment]
Habe ich richtig verstanden, dass es jetzt funktionieren müsste? Bei mir wird der oben angegebene Artikel mit V 0.14 leider weiter nicht berücksichtigt (keine VÖBBot-Animation, keine Einbindung des Genios-Artikels). Auch mit anderen Artikeln geht es nicht. 

Danke auf alle bisherige Arbeit. Das Addon ist wirklich toll!

**Comment by stefanw** [comment]
heise.de macht da während des Seiten-Ladens viel Kram, der DOM ist da nicht ganz stabil. Gerne jetzt mal mit 0.15.0 probieren, kann das selbst nicht richtig überprüfen.

**Comment by niwi-hh** [comment]
Die Animation wird nun angezeigt. Es hat aber bei keinem von vielleicht 10 getesteten Artikeln geklappt, einen Genios-Text eingebunden zu bekommen. Dies ist nur zum Teil dadurch erklärbar, dass Heise Plus tatsächlich exklusiven Content haben könnte. Der oben verlinkte Artikel wird nämlich auch nicht geladen, obwohl er definit in Genios verfügbar ist.

**Comment by niwi-hh** [comment]
Ich muss mich leicht korrigieren: Heise scheint die Überschriften für die Online-Artikel häufig abzuändern. Dies gilt auch für den verlinkten Artikel oben. Man muss statt der Überschrift einem kurzen Ausschnitt aus dem Teaser nehmen. Im Artikel oben führt z.B. "Doch wer jetzt daran denkt, fertige Kabel mit Stecker durch übergroße" zum Ziel.

**Comment by stefanw** [comment]
> Man muss statt der Überschrift einem kurzen Ausschnitt aus dem Teaser nehmen

Genau das sollte schon passieren. Wenn sich das Tab öffnet, kannst du gucken, was gesucht wird. Es sollten die ersten paar Worte des Artikels in Anführungszeichen sein.

**Comment by niwi-hh** [comment]
Gesucht wird zum Beispielartikel oben auf der Geniosseite nach: ""

Die Fehlermeldung auf der Geniosseite lautet dann: "Die von Ihnen verwendete Suchsyntax wird nicht unterstützt. Informationen zur möglichen Suchsyntax finden Sie in der Hilfe." Irgendwas geht also schief.

**Comment by niwi-hh** [comment]
Update: Bei heise+-Artikeln springt das Addon nun nicht mehr an. Auch beim Beispielartikel oben nicht. Ich vermute, Heise hat an der Webseitew geschraubt. Ob sie hier mitlesen? Sie hatten ja bereits über das Addon berichtet...

**Comment by niwi-hh** [comment]
UPDATE: Mit Version 0.17 springt das Addon nun wieder an. Ob es am Update oder Heise liegt, weiß ich nicht. Weiterhin funktioniert es für Heise+ aber nicht. Ich vermute [wie weiter oben](_Originally posted by @niwi-hh in https://github.com/stefanw/voebbot/issues/30#issuecomment-817373159_), dass Genies keine Suchwörter übergeben werden.

**Comment by Wombat2018** [comment]
Bei heise öffnet sich ein Tab mit dem Artikel, dort wird er auch gefunden und der Tab schließt sich, aber der Text wird nicht auf der heise-Website implementiert und es kommt die Meldung, dass der Artikel nicht gefunden werden konnte.

**Comment by niwi-hh** [comment]
Stimmt. Leider gelingt es mir auch nicht, von dem Genios-Tab den Artikel zu laden. Er schließt sich auf jedem Fall - auch wenn man vorher den Artikellink anklickt. Es gelingt mir auch nicht, den Artikel in einen weiteren Tab zu öffnen.

**Comment by Nihlo** [comment]
#228

**Comment by knarxy** [comment]
Hey zusammen, bei mir springt das Addon bei Artikeln auf heise.de leider überhaupt gar nicht erst an, d.h. es öffnet sich kein Genios-Tab und es wird keine Suche eingeleitet. Besteht das Problem so bei euch auch?
Soll ich dafür ein eigenes Issue eröffnen?
Danke vorab für eure kurze Rückmeldung.
