### ISSUE TITLE
Tagesspiegel funktioniert nicht mehr

### ISSUE THREAD

**Issue by DKlemann** [stefanw/bibbot#302]
Beim tagesspiegel wird Bibbot gar nicht mehr aktiv:
- Die Animation wird nicht eingeblendet.
- Es wird kein neuer Tab mit Genios geöffnet.

**Comment by DKlemann** [comment]
(Im Juli ging das auf jeden Fall noch.)

**Comment by sinclair2** [comment]
Hi @DKlemann  :) Es gibt bereits einen Bugfix, siehe #296. Hoffe er wird bald gemerged.

**Comment by sinclair2** [comment]
Es ändern sich immer mal wieder die IDs im HTML DOM, da muss man ab und zu nachsteuern. Ich hab mal einen PR erstellt, der es wieder beheben sollte (lokal bei mir gehts).
