### ISSUE TITLE
Stuttgarter Zeitung/Stuttgarter Nachrichten funktioniert nicht (mehr)

### ISSUE THREAD

**Issue by blumentritt** [stefanw/bibbot#312]
Auf stuttgarter-zeitung.de bzw. stuttgarter-nachrichten.de werden keine Paywall-Artikel mehr erkannt und daher bibbot nicht getriggert. Vor einigen Wochen hat das noch geklappt, scheinbar gab es eine Änderung bei der Paywall.

Beispiele:
STZ:
a) https://www.stuttgarter-zeitung.de/inhalt.gebaeude-des-autobauers-in-stuttgart-dieser-mercedes-stern-verschwindet-fuer-immer.51d9e843-97f4-4f4c-8852-df6141b4db65.html
b) https://www.stuttgarter-zeitung.de/inhalt.bilanz-im-vvs-deutschlandticket-kurbelt-nachfrage-an.bc432a9a-bed3-46f2-a6ce-340275562b0d.html

STN:
a) https://www.stuttgarter-nachrichten.de/inhalt.gebaeude-des-autobauers-in-stuttgart-dieser-mercedes-stern-verschwindet-fuer-immer.51d9e843-97f4-4f4c-8852-df6141b4db65.html

b) https://www.stuttgarter-nachrichten.de/inhalt.bilanz-im-vvs-deutschlandticket-kurbelt-nachfrage-an.bc432a9a-bed3-46f2-a6ce-340275562b0d.html

**Comment by MesserJo-BB-GH** [comment]
Die Webseiten Stuttgarter Zeitung und Stuttgarter Nachrichten funktionieren nicht mehr. Ich habe das schon einmal hier angemerkt, finde aber meinen eigenen Beitrag nicht mehr. Es gibt zwar einen manuellen Trick, aber das Add-On funktioniert nicht mehr. Kann bitte jemand diesen Fehler reparieren?

**Comment by MesserJo-BB-GH** [comment]
Can you please re-open this issue?
