### ISSUE TITLE
Artikel wird nicht abgerufen Nexis Uni (Bib. Bonn)

### ISSUE THREAD

**Issue by sleepy-nols** [stefanw/bibbot#325]
**Expected behaviour:**
Beim öffnen eines Paywall Artikels öffnet sich Nexis Uni zum login. Nach login wird der angefragte Artikel geladen, bzw. in dem Bibbot Fenster angezeigt. 

**Actual behaviour:**
Beim öffnen eines Paywall Artikels öffnet sich das Nexis Uni login Fenster in einem neuen Tab. Nach login passiert nichts und im Bibot fenster steht "Pressedatenbank wird aufgerufen...". Auch nach längerem warten, oder schließen und erneutem öffnen oder Abfragen des Artikels passiert nichts.

GIbt es eine möglichkeit Logs des Plugins abzugreifen?

Getestet auf:
Firefox 118.0.2
Zeit.de
Bib. Bonn

**Comment by pittibaerli** [comment]
ja, bei mir genauso mit Bibliothek Bonn in Chrome. Selbst der Testlink auf den Zeit-Artikel geht nicht. Habe mich sowohl im Plugin also auch auf den Bib-Bonn-Login der aufgepoppt ist, eingeloggt. Was ist das los?

**Comment by DavGoeck** [comment]
Hey, bei mir ist es auch so. Ich bin mir sicher, dass ich die Credentials korrekt hinterlegt habe.

**Comment by sleepy-nols** [comment]
@DavGoeck Bei dir auch nur bei der Bonner Bibliothek?

**Comment by Propi0815** [comment]
Hier auf Android mobil gleiches Verhalten mit dem Kiwi Browser und Firefox. Habe in Kiwi umgestellt, dass die genios.de-Seite als Desktop-Webseite angefordert werden soll (Einstellungen\Website-Einstellungen\Desktop-Website\Aus --> Ausnahme genios.de hinzufügen). Nach einem Neustart des Browsers funktioniert es.

**Comment by pittibaerli** [comment]
warum könnte es denn bei NICHT gehen? Wie gesagt. Daten sind im Plugin eingetragen. Wenn ich den Test-Link (von der  Zeit) anklicke, kommt eine weiterer Browswer-Tab mit dem Login von Stadtbibliothek Bonn fuer Nexis. Logge mich ein. Aber nichts passiert. "BiBot - Pressedatenbank wird augerufen". Darunter eine Animation die die ganze Zeit von links nach rechts und zurueck sich bewegt. 1 Stunde gewartet. Auch Firefox und Edge probiert. Ueberall das gleiche Problem. Wie kann ich helfen, das Problem zu lösen. Danke

**Comment by macros111** [comment]
Bei mir das gleiche Verhalten. Windows + Chrome Extension

**Comment by sleepy-nols** [comment]
Ich habe gerade mal sowohl auf der seite eines Test Artikels als auch auf der Nexis Uni Login seite in der Konsole gelauscht und den Networking Tab angeguckt. Leider nichts auffäliges gefunden. Mir fehlt leider immer noch ein Weg um das Plugin richtig zu debuggen oder Logs auszulesen.

**Comment by DavGoeck** [comment]
@sleepy-nols Ich habe keine weiteren Accounts, deshalb kann ich es nur für Bonn angeben.

**Comment by sleepy-nols** [comment]
Nach weiterem graben schein es wohl ein Permission Problem zu sein
` Uncaught (in promise) Error: Cannot request origin permission for https://*.bonn.idm.oclc.org/* since it was not declared in the manifest `
Falls jemand mit der Codebase vertraut ist, gerne ein MR schreiben.

**Comment by sleepy-nols** [comment]
Habs gefunden, pushe gleich eine MR. :)

**Comment by pittibaerli** [comment]
> Habs gefunden, pushe gleich eine MR. :)

was ist eine MR? ;-)

**Comment by sleepy-nols** [comment]
@pittibaerli Merge Request ;)

**Comment by macros111** [comment]
guckst du:

https://gprivate.com/67j8x

**Comment by DavGoeck** [comment]
@macros111 @sleepy-nols , vielen Dank für die schnelle Reaktion. Hatte schon befürchtet, dass ich jetzt selbst ordentlich wühlen muss in einer unbekannten Codebase!

@pittibaerli, Merge Request und Pull Request sind die zwei hauptsächlichen Varianten, um eigene Änderungen in ein OpenSource Codeprojekt einzubringen. Wenn jemand sagt er macht einen MR/PR, dann heißt das jemand hat den Fehler behoben und wartet auf Prüfung durch den Chef des Projekts, dass die Änderungen auch tatsächlich angewendet werden.

**Comment by pittibaerli** [comment]
ok, verstehe jetzt schon ein wenig mehr. Und jetzt muss der Author des Plugins das ganze noch  "einbauen", ja? Wie lange dauert sowas in etwa? Danke

**Comment by sleepy-nols** [comment]
RIchtig. Das dauert, bis der Repo Besitzer sich Zeit dafür nimmt. ;)
