### ISSUE TITLE
Bug - BSB liefert nur 404 Fehler

### ISSUE THREAD

**Issue by chstdu** [stefanw/bibbot#335]
Beim Test-Artikel "Soziale Ungleichheit - Auf dem Rücken der Arbeiter und der Armen" von zeit.de (und auch bei allen anderen bisher getesteten Artikel) öffnet sich beim ersten Mal eine Login-Seite der Bayerischen Staatsbibliothek (mit Auswahlmöglichkeiten BSB oder LMU), die ich mit einem Klick auf "Anmeldung" bestätige (denn die BSB ist als Default-Option ausgewählt), aber dann kommt nur folgende 404-Fehlerseite:
![NotFoundBib](https://github.com/stefanw/bibbot/assets/1130593/a9b88642-2e39-48e6-a2a7-e7193497770c)

Bei erneutem Versuchen kommt dieselbe Fehlermeldung, aber manchmal eine längere URL mit Query-Parametern: https://www-1wiso-2net-1de-1001394go0ffe.emedia1.bsb-muenchen.de/dosearch?explicitSearch=true&q=%22eine%20gesellschaftliche%20Gruppe%20ihre%20Anliegen%20vorbringt%20ihren%20Schmerz%20ausspricht%20wird%20davor%20gewarnt%20dies%22&dbShortcut=ZEIT%2CZEIO%2CZTCS%2CZTGS%2CZTWI%2CCUW&TI%2CUT%2CDZ%2CBT%2COT%2CSL=&AU=&KO=&MM%2COW%2CUF%2CMF%2CAO%2CTP%2CVM%2CNN%2CNJ%2CKV%2CZ2=&CT%2CDE%2CZ4%2CKW=&Z3%2CCN%2CCE%2CKC%2CTC%2CVC=&DT_from=08.03.2021&DT_to=13.03.2021&timeFilterType=selected&timeFilter=NONE&x=59&y=11

Hier noch die Details aus der Extension-Console:
```
tab created 411986508
background.js:2476 tab load complete 411986508
background.js:2496 loggedin? [false]0: falselength: 1[[Prototype]]: Array(0)
background.js:2318 Running {click: '#submitbutton'}click: "#submitbutton"[[Prototype]]: Object
background.js:2476 tab load complete 411986508
background.js:2318 Running {fill: {…}}fill: {selector: 'input[name="username"]', providerKey: 'www.bsb-muenchen.de.options.username'}[[Prototype]]: Object
background.js:2318 Running {fill: {…}}fill: {selector: 'input[name="password"]', providerKey: 'www.bsb-muenchen.de.options.password'}[[Prototype]]: Object
background.js:2318 Running {click: '#btnLogin'}click: "#btnLogin"[[Prototype]]: Object
background.js:2476 tab load complete 411986508
background.js:2318 Running {url: 'https://www-1wiso-2net-1de-1001394go0ffe.emedia1.b…timeFilterType=selected&timeFilter=NONE&x=59&y=11'}
background.js:2476 tab load complete 411986508
background.js:2318 Running {failOnMissing: '.boxHeader', failure: 'Artikel nicht gefunden'}failOnMissing: ".boxHeader"failure: "Artikel nicht gefunden"[[Prototype]]: Object
background.js:2595 Error: Artikel nicht gefunden
``` 

Wäre cool, wenn man das Fixen könnte. Ich stelle gerne weitere Infos bereit, wenn man mir sagt, wie ich diese erstellen kann.

**Comment by chstdu** [comment]
Wenn ich mich bei der BSB nach WISO durchklicke erhalte ich gerade folgenden Link: https://www-1wiso-2net-1de-101vwux4k170d.emedia1.bsb-muenchen.de/dosearch

Und damit wird dann auch der Test-Artikel gefunden, siehe Screenshot:

![image](https://github.com/stefanw/bibbot/assets/1130593/12ea01dd-262e-483e-9c30-f2ec0db6750c)

**Comment by chstdu** [comment]
Und hier noch ein Screenshot der erwähnten Anmelde-Seite mit den beiden Antwortoptionen:
![image](https://github.com/stefanw/bibbot/assets/1130593/5ad18e64-abaa-4e2a-88b9-05c2d66981c4)

**Comment by stefanw** [comment]
Die Proxy-Domain ist offenbar dynamisch generiert und lässt sich nicht fest einstellen. Um das zu Beheben brauche ich zum Testen Zugangsdaten (vertraulich, per E-Mail).
