### ISSUE TITLE
Freie Presse

### ISSUE THREAD

**Issue by schnurpser** [stefanw/bibbot#34]
**URL der Nachrichtenseite**
https://www.freiepresse.de

**URL zu einem Artikel mit Paywall**
https://www.freiepresse.de/chemnitz/neue-schau-im-wasserschloss-klaffenbach-tiere-musik-und-schokolade-artikel11437998

**Ist die Nachrichtenseite bei Genios enthalten?**
Bitte bei Genios https://bib-voebb.genios.de/ unter Quellen -> Alle Quellen prüfen.

Ja   (mind. über https://www.ebibo-dresden.de/)

**Comment by Priphy** [comment]
Auch hier nochmal: Die Seite ist definitiv bei Genios unter dem Kürzel FEPR abrufbar.
