### ISSUE TITLE
piHole

### ISSUE THREAD

**Issue by ScrewedDriver** [stefanw/bibbot#342]
Wäre es evtl. möglich den BibBot irgendwie in PiHole zu integrieren? So wäre es möglich, den BibBot auch mit mobilen Geräten im Heimnetz zu nutzen.

**Comment by stefanw** [comment]
Meines Wissens nach arbeitet piHole mit DNS, BibBot ist eine Browser-Erweiterung – und DNS vermag das nicht zu leisten. Bzgl. mobile Geräte: es gibt da ggf. demnächst mehr Optionen (z.B. Firefox mobile extensions auf Android).
