### ISSUE TITLE
tagesspiegel.de not triggering with Safari plugin

### ISSUE THREAD

**Issue by charlesvestal** [stefanw/bibbot#343]
The plugin appears to not be triggering with Tagesspiegel using the Safari plugin.

An example [URL](https://www.tagesspiegel.de/politik/interview-mit-dem-migrationsexperten-knaus-es-gibt-eine-politische-falle-10669765.html) will trigger in Firefox and Chrome, but has no effect on Safari.

I believe the plugin is otherwise functioning properly as Zeit.de behaves as expected.

Safari Version 17.0 (19616.1.27.211.1)
Plugin 0.26.8

**Comment by stefanw** [comment]
The current version is v0.28.0. The Safari plugin does not update automatically due to the way it has to be installed. Please download an update and follow the steps on the website.
