### ISSUE TITLE
Bayerische Staatsbibliothek funktioniert nicht

### ISSUE THREAD

**Issue by fabiang** [stefanw/bibbot#346]
Laut Reviews bei Google funktioniert die Bayerische Staatsbibliothek nicht mehr.

Kann es sein, dass das lediglich die Domain geändert werden muss auf https://idp.bsb-muenchen.de/idp/Authn/BSB?conversation=e2s1, da die BiB eine Seite vor der anderen geschaltet hat?

**Comment by bastigruenwald** [comment]
Duplicate von #178
