### ISSUE TITLE
NWZ nwzonline Nordwest-Zeitung nwzonline.de Oldenburg

### ISSUE THREAD

**Issue by PaulEins** [stefanw/bibbot#348]
**URL der Nachrichtenseite**
https://www.nwzonline.de/

**URL zu einem Artikel mit Paywall**
https://www.nwzonline.de/oldenburg/oldenburg-jade-hochschule-75-jahre-an-ofener-strasse_a_51,7,3635416836.html

**Ist die Nachrichtenseite bei Genios enthalten?**
ja
https://www.genios.de/searchResult/Alle?requestText=nwz&source=Nordwest-Zeitung&size=10&sort=BY_DATE&order=desc&resultListType=DEFAULT&view=list

**Comment by PaulEins** [comment]
Ich hab gerade einen Account in Berlin erstellt und kann auf die RegionalZeitung zugreifen.

Kann es sein, dass es nur in die Erweiterung eingebunden werden muss?
Hier ein Foto:
<img width="1112" alt="Bildschirmfoto 2023-11-03 um 16 10 49" src="https://github.com/stefanw/bibbot/assets/89552633/11eb8561-59cb-4fde-9050-660e6b08b5c0">

**Comment by PaulEins** [comment]
Und ich hab das hier gefunden:
<img width="1470" alt="Bildschirmfoto 2023-11-03 um 16 43 24" src="https://github.com/stefanw/bibbot/assets/89552633/075c9dbb-f62f-432d-a1d2-3a75ea946b5f">

**Comment by stefanw** [comment]
NWZ enthält den Artikel-Text auch in einem JSON-Objekt im HTML. Hole das jetzt da raus, nicht schön, aber zum Lesen reichts.

**Comment by PaulEins** [comment]
Magst nochmal schauen. Haben die das JSON - Objekt verändert? Ich würde mit meinen Amateurfähigkeiten sagen, dass der text nicht mehr im Quellcode steht. Haben die hier das gelesen udn eventuell gezielt verändert?

Ist das nun so ein Katz und Maus spiel, dass die das wieder ändern? Vermutlich lohnt sich dass dan nicht.

Kannst du das über die Bücherrei eimbinden?

PS. Ich hab vielen deine App eingerichtet oder gezeigt. Alle waren begeistert.
Und Magst mir eine lese bestätigung geben? Dann weiß ich, dass diese Info bei dir angekommen ist. =)
Sonst würde ich die Tage einen neune Beitrag schreiben.
