### ISSUE TITLE
Kann man BibBot für Seiten ausstellen, für die man Abonnent ist?

### ISSUE THREAD

**Issue by Reselatte** [stefanw/bibbot#357]
Es gibt Zeitungen, die ich so gut finde, dass ich sie durch ein Abo unterstützen möchte. Leider habe ich (noch) keine Möglichkeit gefunden, BibBot für diese auszuschalten. Die Originalseiten enthalten z.T. mehr _features_, die durch BibBot abgeschaltet werden. Das ist schade.

**Comment by stefanw** [comment]
Seit v0.30.0 in den BibBot-Einstellungen unter „Weitere Einstellungen“ -> „BibBot auf diesen Seiten deaktivieren“

**Comment by Reselatte** [comment]
Vielen Dank!

**Comment by koehntopp** [comment]
> Seit v0.30.0 in den BibBot-Einstellungen unter „Weitere Einstellungen“ -> „BibBot auf diesen Seiten deaktivieren“

Wie genau stellt man das ein - ich sehe eine Liste, kann aber pro Eintrag nicht erkennen, ob aktiviert oder deaktiviert?

![image](https://github.com/stefanw/bibbot/assets/7113567/1e4ac829-e44d-4750-a978-3d0f6a5db7ce)

**Comment by stefanw** [comment]
Das ist ein Standard-Mehrfachauswahl-Feld. Wenn es (hier blau) hinterlegt ist, ist es aktiviert, sonst nicht.
