### ISSUE TITLE
Stadtbibliothek Dresden funktioniert nicht mehr

### ISSUE THREAD

**Issue by honki2k** [stefanw/bibbot#360]
Hi,

seit 2 Wochen wird automatisch auf einen neue Seite umgeleitet:
- alt / geht noch: [https://sbdresden.genios.de/global/index](https://sbdresden.genios.de/global/index)
- neu / geht nicht mehr:  [https://sbdresden.genios.de/](https://sbdresden.genios.de/)

Hoffe Du kannst das fixen. BTW: Sehr schönes Projekt!

Grüße
Steven

**Comment by merula75** [comment]
Das Problem ist die neue login Seite. Bislang tat es (vermutlich) der Genios default. Jetzt bräuchte es in der provider.ts einen extra Eintrag für die Bibo Dresden, bei denen die Login-Daten in etwa so aussehen:
```
        login: [
            [
                { message: 'Bibliothekskonto wird eingeloggt...' },
                { fill: { selector: 'input[name="ad_fo_el_1"]', key: 'options.username' } },
                { fill: { selector: 'input[name="ad_fo_el_2"]', key: 'options.password' } },
                { click: 'input[type="ad_fo_el_termsAndConditions"]' },
                { click: 'input[type="ad_fo_el_privacyPolicy"]' },
                { click: 'input[type="submit"]' }
            ]
        ],
```
Wie genau das geht habe ich noch nicht raus. Ich versuche mir gerade die Buildumgebung aufzusetzen - bin nicht so der Webentwickler.

**Comment by traubenzuckerberg** [comment]
Das dürfte dasselbe Problem sein, das hier beschrieben wurde:
https://github.com/stefanw/bibbot/issues/320

(Hier auch noch einmal: https://github.com/stefanw/bibbot/issues/324)

Soweit ich das verstehe, wurde es mit diesem Beitrag behoben https://github.com/stefanw/bibbot/pull/327 , aber nicht immer noch nicht eingebaut.

**Comment by merula75** [comment]
@traubenzuckerberg #327 wird das Problem (für die Bibo Dresden) nicht lösen, weil der neu angelegte Provider nur bei der Bibo Essen eingetragen ist. Ich werde mal alle Bibliothekseinträge durchgehen und dort einen entsprechende Kommentar hinterlassen.

**Comment by stefanw** [comment]
Behoben in v0.31.0.

**Comment by merula75** [comment]
@stefanw endlich geht es wieder. :-) Github Sponsorship hat nur noch VISA. :-( Kann man Dir auch was per paypal oder Überweisung zukommen lassen (wie toll der bitbot ist, merkt man erst, wenn er nicht mehr tut)?
