### ISSUE TITLE
bib-voebb.genios.de Landing Page geändert und bibbot-Suchen funktionieren nicht mehr

### ISSUE THREAD

**Issue by Milszus** [stefanw/bibbot#364]
bib-voebb.genios.de hat die Landing Page geändert und bibbot-Suchen funktionieren nicht mehr.

**Comment by Milszus** [comment]
Blöd auch, dass bei einer fehlgeschlagenen Suche der Suchstring nicht mehr zu sehen (und damit zu verfeinern oder ähnliches) ist.

**Comment by ljrk0** [comment]
> Blöd auch, dass bei einer fehlgeschlagenen Suche der Suchstring nicht mehr zu sehen (und damit zu verfeinern oder ähnliches) ist.

Ah, das liegt daran, dass sich die Syntax etwas verändert hat.  Fixt man den Suchstring wie ich angegeben, dann geht das :-)

Sprich, sobald das neue GENIOS als source hinzugefügt wurde ist zumindest in der Hinsicht alles wieder beim Alten.

**Comment by stefanw** [comment]
Behoben in v0.31.0.
