### ISSUE TITLE
Bug: Extension öffnet Genios für "Stadtbibliothek Nürnberg im Bildungscampus" nicht

### ISSUE THREAD

**Issue by 5H00T4** [stefanw/bibbot#368]
Ich habe die Erweiterung für Chrome gestern in einer Vielzahl von Browsern getestet und bin beinahe verzweifelt, da ich mir extra einen Bibliotheksausweis dafür geholt habe und es einfach nicht gehen wollte.

Wenn ich in den Bibbot-Einstellungen die Stadtbibliothek Nürnberg im Bildungscampus (https://www.nuernberg.de/internet/stadtbibliothek/) auswähle dann öffnet sich immer nur ein neuer Chrome Tab mit mit folgender URL:
`chrome-extension://edafomjglmkfbiieocpflnhfdmikkhbo/%7Bsource.scheme.raw%7Dbib-nuernberg.genios.de/`
und der Meldung 
```
Zugriff auf die Datei nicht möglich
Eventuell wurde sie verschoben, bearbeitet oder gelöscht.
ERR_FILE_NOT_FOUND
```

Da ist es auch egal was ich als Logindaten eingebe, soweit kommt man erst gar nicht.
Wird eine andere Bibliothek ausgewählt dann erscheint zumindest das Loginfenster.
Der Aufruf speziell für Nürnberg scheint also irgendwie kaputt zu sein.

**Comment by stefanw** [comment]
Das ist ein Bug in der neuesten Version.

**Comment by stefanw** [comment]
Sollte hoffentlich in v0.31.1 behoben sein.

**Comment by 5H00T4** [comment]
> Sollte hoffentlich in v0.31.1 behoben sein.

Also die Genios Seite wird jetzt korrekt geöffnet, der Artikel wird auch in diesem neuen Tab angezeigt, auf der Paywall-Seite wird aber von Bibbot nur angezeigt:
```
BibBot
Artikel konnte nicht gefunden werden
```

Geht selbst mit der Zeit.de Testseite nicht.
Irgendwas ist da noch im Argen...
