### ISSUE TITLE
Kein Update des Addons in Firefox

### ISSUE THREAD

**Issue by Alucard712** [stefanw/bibbot#369]
Moins.

Ich habe mich in den letzten Wochen gewundert und geärgert, dass der Bot seit dem Redesign der Genios-Seite nicht mehr funktioniert.

Erklärung: Mein FF-Addon hing noch auf Version 0.25 aus März '23 fest. FF hat sich leider standhaft geweigert es zu aktualisieren. Ich musste es jetzt händisch deinstallieren und neu über die FF-Addon-Seite installieren, wo es die aktuelle Version ja tatsächlich auch gab - hat natürlich die Settings gekillt.

Ist das sonst noch bei jemandem passiert?

**Comment by stefanw** [comment]
BibBot war lange nicht im Firefox Add-On Store, sondern war nur von Mozilla signiert (die erste Version wurde damals nicht reingelassen). Das hat sich aber geändert und die Umstellung von Nicht-Store auf Store-Add-On ist vermutlich als Update nicht möglich gewesen(?).

**Comment by Alucard712** [comment]
Ah, ok - thx. Das könnte es erklären.
