### ISSUE TITLE
Dateien unter moz-extension://0b40000a-f9b7-451c-9912-7b848740bda/{source.scheme.raw}buecherhallen.genios.de/ konnten nicht gefunden werden

### ISSUE THREAD

**Issue by niwi-hh** [stefanw/bibbot#371]
Wenn das Addon eine beliebige Seite öffnen will, kommt seit kurzem folgende Fehlermeldung:

Die Dateien unter moz-extension://0b30000a-f6b7-311c-9912-7b332741bda/{source.scheme.raw}buecherhallen.genios.de/ konnten nicht gefunden werden.

Die Zahlen oben habe ich vorsichtshalber geändert.

**Comment by stefanw** [comment]
Sollte in neuester Version behoben sein.
