### ISSUE TITLE
Bug: kein automatischer Login bei Genios und keine Anzeige der Artikel

### ISSUE THREAD

**Issue by 5H00T4** [stefanw/bibbot#373]
Hi, Bug 368 wurde bereits geschlossen, aber es gibt da zumindest für die Bibliothek Nürnberg immer noch Fehler.

1. Genios-Tab öffnet sich, aber kein automatischer Login
2. Also die Genios Seite wird jetzt korrekt geöffnet, der Artikel wird auch in diesem neuen Tab angezeigt, auf der Paywall-Seite wird aber von Bibbot nur angezeigt:

```
BibBot
Artikel konnte nicht gefunden werden
```

Geht selbst mit der Zeit.de Testseite nicht.
Irgendwas ist da noch im Argen...

_Originally posted by @5H00T4 in https://github.com/stefanw/bibbot/issues/368#issuecomment-1817465640_

**Comment by 5H00T4** [comment]
Wenn ihr weitere Unterstützung oder einen Account für Tests braucht sagt Bescheid.

**Comment by stefanw** [comment]
Konto für tests wäre gut.

**Comment by stefanw** [comment]
Nürnberg hat ja offenbar eine eigene Login-Seite, da lässt sich ohne Zugangsdaten nur raten wie das funktioniert. Gerne vertraulich per Mail.

**Comment by 5H00T4** [comment]
> Nürnberg hat ja offenbar eine eigene Login-Seite, da lässt sich ohne Zugangsdaten nur raten wie das funktioniert. Gerne vertraulich per Mail.

Ja das ist richtig, weiß ja nicht wie das bei den anderen ist.
Habs dir ne Mail geschickt.
Danke. :)

**Comment by stefanw** [comment]
Nach Upgrade auf v0.32.0 bitte einmal die Einstellungsseite besuchen und dort neue Berechtigungen erlauben (Knopf unten rechts).

**Comment by 5H00T4** [comment]
Jawoll, funktioniert jetzt!
Vielen Dank! 👍
