### ISSUE TITLE
Artikelö werden in Genios gefunden, aber nicht integriert

### ISSUE THREAD

**Issue by niwi-hh** [stefanw/bibbot#374]
BibBot bindet die eindeutig gefundenen Artikel bei mir nicht mehr ein. Getestet habe ich dies mit Version BibBot v0.31.1, Firefox und den Hamburger Bücherhallen (Genios).

Hier vier Beispiellinks:
- https://www.welt.de/politik/deutschland/plus248568662/Ricarda-Lang-Das-zu-finanzieren-sind-wir-den-Menschen-schuldig.html?source=puerto-reco-2_ABC-V34.0.C_without_polys
- https://www.sueddeutsche.de/wirtschaft/dick-im-job-uebergewicht-gehalt-vorurteile-was-tun-1.6304133?reduced=true
- https://www.zeit.de/politik/ausland/2023-11/suedkorea-geburtenrate-frauen-feminismus-metoo
- https://www.zeit.de/2021/11/soziale-ungleichheit-identitaetspolitik-diskriminierung-armut-bildung

Der vierte Links ist der Test-Links aus den Einstellungen.

**Comment by stefanw** [comment]
Sollte in v0.31.2 behoben sein.
