### ISSUE TITLE
Wiso-net.de SSO Erfordert jedes mal einen SSO Login (Cookie expiry überschreiben?)

### ISSUE THREAD

**Issue by rklasen** [stefanw/bibbot#378]
Hi, erstmal danke für die großartige Erweiterung.

Ich bin eingeschrieben an der Ruhr Uni Bochum, und der Wiso-net.de SSO Shibboleh login funktioniert. Allerdings muss ich mich jedes Mal bei dem RUB SSO einloggen, wenn ich den Browser neu starte. Ist das normal?

Browser: Chrome mit lediglich zwei Addons, bibbot und ublock origin (kein Cookie Auto delete oder vergleichbares). Nach allem, was ich in den Chrome Settings gefunden habe, sollten Cookies nicht automatisch gelöscht werden.

Ich sehe in den dev tools, dass die Cookies auf wiso-net.de als expiry "Session" haben (ich schätze das beantwortet die Frage eigentlich schon).

Ich habe die expiry von Hand auf 2025-01-01 gesetzt und jetzt überlebt der Login einen Browser Neustart. Daher meine Frage:

Gibt es eine Möglichkeit in Bibbot, diese expiry für Cookies auf wiso-net.de zu überschreiben? Ich habe keine Ahnung, wann die session Cookies auf der Serverseite ihre Gültigkeit verlieren,  aber zumindest müssen sie ja nicht bei jedem Neustart verfallen.

Vielen Dank!

**Comment by stefanw** [comment]
Session cookies werden beim Browser-Neustart gelöscht, siehe auch https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

Cookie-Manipulation ist out of scope für das Add-On.
