### ISSUE TITLE
Stadtbibliothek Freiburg: Login bei bawue.genios.de funktioniert nicht mehr

### ISSUE THREAD

**Issue by traeu** [stefanw/bibbot#385]
Ich hatte bisher erfolgreich einen Login der Stadtbibliothek Freiburg hinterlegt.
Wenn ich aktuell den Test-Artikel aus den Bibbot-Einstellungen öffne, öffnet sich wie gewohnt im Hintergrund ein Tab von https://bib-bawue.genios.de/, um den Artikel zu suchen. 
Dort funktioniert aber der Login nicht mehr. 
Ich erhalte die Fehlermeldung "Ihre Anmeldeinformationen sind ungültig. Bitte überprüfen Sie Ihre Benutzernummer, Ihr Passwort oder ausstehende Zahlungen."
Der Login direkt auf der Seite der Stadtbibliothek Freiburg (https://www.onleihe.de/freiburg/) funktioniert noch.

Ich bin mir unsicher, ob das ein Problem ist, das Bibbot beheben kann.
Möglicherweise ein ähnliches Problem wie Issue #383.

**Comment by reinholdeins** [comment]
Hi, ich hatte exakt das gleiche Problem. 
Die Stadtbibliothek Freiburg scheint heimlich still und leise das Passwortformat geändert zu haben.

Alt: TTMMJJ
Neu: TTMMJJJJ

Bei mir läuft nun wieder alles.

Danke an dieser Stelle auch allgemein für den BibBot!

**Comment by traeu** [comment]
Danke für den Hinweis, das ist die Lösung!
Interessant, dass zu der Zeit, als ich es bemerkt habe, das alte Passworformat noch bei onleihe.de akzeptiert wurde, aber bereits nicht mehr bei genios.
