### ISSUE TITLE
Feature-Request: Seiten ignorieren

### ISSUE THREAD

**Issue by xnorxnor** [stefanw/bibbot#39]
Erst mal danke für das tolle Addon 👍 
Da ich teilweise Abos für bestimmte Seiten habe, würde ich das Addon gerne für einzelne Seiten deakvieren. Lässt sich das leicht implementieren?

**Comment by stefanw** [comment]
Was passiert denn gerade mit Abo? Die Paywall wird ja vermutlich mit Abo nicht im Artikel angezeigt und ohne Paywall wird das Add-On auch nicht aktiv.

**Comment by p-mng** [comment]
Fände das Feature auch interessant, weil die [bypass-paywalls-chrome](https://github.com/iamadamdev/bypass-paywalls-chrome)-Erweiterung [bereits SZ Plus-Artikel durch Weiterleitung "entsperren" kann](https://github.com/iamadamdev/bypass-paywalls-chrome/blob/416d0c11ab4298acf87abd6148c61b6b77baaa1f/src/js/contentScript.js#L528). Der voebbot versucht dann nach der Weiterleitung einen falschen Titel bei GENIOS zu suchen.

**Comment by outbacker** [comment]
Das fände ich auch äußerst praktisch. Einfach, weil ich nicht ständig bei sämtlichen Seiten eingeloggt bin, für die ich ein Abo habe.
Und anstatt dass ich mich dann simpel mit meinem Passwortmanager einloggen kann, muss ich erstmal das sich öffnende Popup blocken sowie die Seite neu laden, damit die Loginfelder wieder angezeigt werden.

**Comment by BenutzerEinsZweiDrei** [comment]
bypass-paywalls-chrome funktioniert bspw auch nicht zusammen mit Unpaywall. Ich mache es momentan so, dass ich für jedes Addon einen eigenen Browser nutze.

**Comment by stepro-de** [comment]
Ich möchte das nochmal in den Vordergrund holen. Tatsächlich muss ich das Plugin die meiste Zeit deaktiviert lassen, weil ich sonst die von mir abonnierte Thüringer Allgemeine nicht lesen kann. Angemeldet mit aktiviertem Plugin lädt sich jede Seite tot.

**Comment by CmdrMichael** [comment]
Ja, nerviger Bug. Seiten die man im Abo hat kann man dadurch nicht lesen. Bitte eine URL-basierte Deaktivierungsfunktion für das Plugin einbauen.
