### ISSUE TITLE
Stadtbibliothek Koblenz

### ISSUE THREAD

**Issue by KKairat** [stefanw/bibbot#390]
**URL des Digitalangebots der Bibliothek**
https://www.koblenz.de/leben-in-koblenz/kultur/stadtbibliothek/konto-katalog/

**Hat die Bibliothek eine Pressedatenbank wie Genios oder LexisNexis im Angebot?**

Falls nicht, funktioniert die Erweiterung mit der Bibliothek leider nicht. 
Falls ja, gib bitte die URL zu der Pressedatenbank an:
https://www.onleihe.de/koblenz/frontend/welcome,51-0-0-100-0-0-1-0-0-0-0.html

**Comment by stefanw** [comment]
Duplikat von #120.

**Comment by pictosun** [comment]
Und wo ist die Lösung? Klappen tut es ja trotzdem nicht.
