### ISSUE TITLE
https://bib-nuernberg.genios.de Neues Genios Layout, keine Suche nach Artikel

### ISSUE THREAD

**Issue by 5H00T4** [stefanw/bibbot#391]
Der automatische Aufruf von Artikel der Stadtbibliothek Nürnberg im Bildungscampus (https://www.nuernberg.de/internet/stadtbibliothek/) funktioniert nicht mehr.
Nehme an es ist das selbe Problem wie bei #377 & #383 

Zugangsdaten für Test müsstest du noch haben @stefanw :).
Vielen Dank im Voraus.

**Comment by stefanw** [comment]
Ist auf das neue UI umgestellt in v0.34.0
