### ISSUE TITLE
Stadtbibliothek Darmstadt - Keine Reaktion

### ISSUE THREAD

**Issue by Skaitytojas** [stefanw/bibbot#392]
Nachdem es (unter Firefox) einige Wochen wieder gut funktionierte, geht jetzt gar nichts mehr: Bei Spiegel Online z.B. erscheint nur noch der Titel, ein Bild und das war's. Nicht einmal mehr das Login-Fenster von Genios öffnet sich ...

**Comment by Titule1** [comment]
Habe das gleiche Problem.
Es öffnet sich kein Tab und der Artikel enthält lediglich die Überschrift,

**Comment by electrix7** [comment]
Gleiches Problem.
Seit v0.33 funktioniert es bei mir im Firefox mit verschiedenen Bibliotheken nicht mehr.
Mit Chrome dagegen funktioniert es noch.

**Comment by Skaitytojas** [comment]
Bei mir besteht das Problem auch nur unter Firefox. Habe die Erweiterung jetzt mal in Chrome probiert, und siehe da: Es geht! Vielen Dank für den Hinweis!

**Comment by schmarra** [comment]
Das Problem wurde bei mir mit der 033.1 behoben - sowohl für die mobile Variante in Firefox Nightly als auch im normalen Browser

**Comment by PaulEins** [comment]
@Skaitytojas @Titule1 @electrix7 @schmarra @drdaxxy Darf ich euch fragen, ob dem Entwickler unsere Probleme bewusst sind. Wisst ihr das? Ich bin nicht so oft hier. Einerseits sehe ich, dass es updates gibt. Es gibt neue Versionen die beim mir auf macOS mit Chrome auch automatisch drauf sind.

Anderseits sehe ich viele Beiträge in issues, dass da kein kommentar oder keine Reaktion ist. Ich weiß nicht ob ich ihn direkt anschreiben soll, oder ob er das alles sieht und anders beschäftigt ist. Das ist sein gutes Recht.

Was meint ihr? Wird bei mir die NWZ oder die anderen Seite bald wiede rgehen? Diese Sache mit dem JSON, meint ihr, die geht wieder? Könnt irh da mal nachschauen? Oder hat die RegionalZeitugn das entfernt. Wegen dieser Erweiterung hier. =)

**Comment by Skaitytojas** [comment]
Ich bin nur User, aber es ist offensichtlich, dass sich der Entwickler um die Probleme kümmert. Immerhin wurden sie ja gelöst. Es dauert wahrscheinlich ein bisschen, da er das ehrenamtlich macht. Bei mir funktioniert es jedenfalls auch unter Firefox wieder. Nur die letzten Tage von 2023 nicht, was aber an meiner Bibliothek lag, deren Recherchevolumen im vierten Quartal ausgeschöpft war.

**Comment by stefanw** [comment]
Es gab ein Problem in Firefox, das behoben wurde, vermutlich ging es darum. Falls nicht, gerne wieder öffnen. Bitte habt Verständnis, dass meine Kapazität für Support limitiert ist.
