### ISSUE TITLE
[Neues Genios Desing] Liechtensteinische Landesbibliothek Vaduz / https://bib-ostschweiz.genios.de

### ISSUE THREAD

**Issue by no2spc** [stefanw/bibbot#397]
Die Bibliotheken der Ostschweiz (https://bib-ostschweiz.genios.de, u.a. die Liechtensteinische Landesbibliothek in Vaduz) haben ebenfalls umgestellt auf das neue Genios Design, daher werden bei Version 0.33.0 keine Artikel mehr gefunden.

**Comment by stefanw** [comment]
Fixed im nächsten Release.
