### ISSUE TITLE
sueddeutsche.de Fehler: Accessing from Xray wrapper is not supported. 

### ISSUE THREAD

**Issue by Strubbl** [stefanw/bibbot#398]
### URL der Nachrichtenseite

https://www.sueddeutsche.de

### URL zu einem Artikel mit Paywall

https://www.sueddeutsche.de/projekte/artikel/politik/lkw-unfaelle-beim-abbiegen-im-toten-winkel-e744638/?reduced=true

### Ist die Nachrichtenseite in einer Pressedatenbank enthalten?

munzinger

### URL zu der Quellenseite in der Pressedatenbank

\-

### Weitere Details

Wenn ich den SZ-Artikel https://www.sueddeutsche.de/projekte/artikel/politik/lkw-unfaelle-beim-abbiegen-im-toten-winkel-e744638/?reduced=true aufrufe, bekomme ich folgende Fehlermeldung in der console:

```
Error: Accessing from Xray wrapper is not supported. content.js:2869:43
    setupUI moz-extension://67c9eda6-651d-41ba-a1e9-82409b63d6e3/build/content.js:2869
    startInfoExtraction moz-extension://67c9eda6-651d-41ba-a1e9-82409b63d6e3/build/content.js:2877
    start moz-extension://67c9eda6-651d-41ba-a1e9-82409b63d6e3/build/content.js:2851
    start moz-extension://67c9eda6-651d-41ba-a1e9-82409b63d6e3/build/content.js:2845
    (Async: setTimeout handler)
    start moz-extension://67c9eda6-651d-41ba-a1e9-82409b63d6e3/build/content.js:2845
    <anonymous> moz-extension://67c9eda6-651d-41ba-a1e9-82409b63d6e3/build/content.js:3031
    (Async: EventListener.handleEvent)
    <anonymous> moz-extension://67c9eda6-651d-41ba-a1e9-82409b63d6e3/build/content.js:3030
    inject resource://gre/modules/ExtensionContent.sys.mjs:581
    AsyncFunctionNext self-hosted:852
```

content.js:2869 entspricht https://github.com/stefanw/bibbot/blob/d429b128ff9c391fe0c44c9e9474c86e8ad2ed44/src/sitebot.ts#L61 und meint wohl das `[sheet]`

**Comment by Strubbl** [comment]
Ich habe den Fehlerbericht https://bugzilla.mozilla.org/show_bug.cgi?id=1766909 gelesen, der mich zu https://bugzilla.mozilla.org/show_bug.cgi?id=1827104, wo ein Workaround mittels `shadow.adoptedStyleSheets.push(CSSStyle)`, aber der hat auch nicht funktioniert. Ein Fehlerbericht auf den noch verwiesen wird und der noch offen ist, ist https://bugzilla.mozilla.org/show_bug.cgi?id=1751346

**Comment by stefanw** [comment]
Fixed in v0.33.1 (Details in https://github.com/stefanw/bibbot/commit/d6923ddc3085413259d7b11df92ea1e3b3289433)
