### ISSUE TITLE
BUG: Bibbot v0.33.0 broken on macOS Firefox

### ISSUE THREAD

**Issue by apropox** [stefanw/bibbot#401]
Hej!

I am using Bibbot 0.33.0 with Firefox 121.0 (64-bit) on mac OS 14.1.2 (23B92) in a pretty vanialla configuration. But even when I disable all other extensions ( I manily just use uBlock Origin and Privacy Badger) the following behaviour happens every time I load a page eg. the test link in the extenison settings:

- the "fad-out" of the first shown paragraph is removed
- the Bibbot loading rectangle does not appear, nor anything indicating that something is loading
- at frist glance coud not find anything in the devtools, no Bibbot events logged to console

After downgrading Bibbot v.032.1 everything works fine again.

Best & thanks in advance

**Comment by McCisie** [comment]
Having the same issue, with an activated BitBot extension, the overlay for the Paywall is not showing up at all, so BibBot won't start working at all. Deactivation of BibBot shows the overlay again, all other extensions are disabled.

Tested on spiegel.de and zeit.de with current Firefox version 121.0 on Windows 10 with all updates.

A fix for this would be appreciated a lot!

Example from https://www.spiegel.de/auto/fahrberichte/volvo-ex30-im-test-dieses-elektro-suv-stellt-bmw-und-mercedes-bloss-a-12df2c22-d18a-406c-93e7-9a7096f7a2e1

![grafik](https://github.com/stefanw/bibbot/assets/68681839/5c546172-88a2-4fed-a607-599eb91df182)

**Comment by emtiu** [comment]
Same here, Bibbot v0.33.0 on Firefox 119.0.1 on Ubuntu Linux.

**Comment by stefanw** [comment]
Fixed in v0.33.1 (Details in d6923ddc3085413259d7b11df92ea1e3b3289433)
