### ISSUE TITLE
Berliner Morgenpost Bibbot Suche startet nicht.

### ISSUE THREAD

**Issue by Neruk** [stefanw/bibbot#413]
**URL:**
 https://www.morgenpost.de/

**URL zu einem Artikel mit Paywall:**
https://www.morgenpost.de/berlin/article241367286/Radschnellwege-durch-Berlins-Zentrum-Kosten-steigen-weiter.html

**Ist die Nachrichtenseite in einer Pressedatenbank enthalten?**
Genios (https://bib-voebb.genios.de/)

**URL zu der Quellenseite in der Pressedatenbank**
https://bib-voebb.genios.de/searchResult/Alle%20Quellen/Presse?requestText=Die+Ost-+und+West-Route+soll+eine+Radschnellverbindung+mitten+durch+Berlin+schaffen.+Jetzt+startet+die+n%C3%A4chste+Planungsphase.&size=10&sort=BY_DATE&order=desc&resultListType=DEFAULT&view=list&document=BMPO__031b9e69923b57fb89231dfa7d16e0c5d18c6985

**Weitere Details**
Hi, seit einiger zeit geht der Bibbot auf https://www.morgenpost.de/ nicht mehr, er ist nicht mal mehr zusehen (sieht aus, als ob ich ganz ohne Bibbot unterwegs wäre) heißt, das kleine Feld mit "Bibbot sucht den Artikel, etc.." ist nicht mal zusehen. Die Berliner Morgenpost ist natürlich weiterhin in der Pressedatenbank von Genios verfügbar. Andere Seiten wie z.B. https://www.tagesspiegel.de/ funktionieren weiterhin ohne Probleme.
Wie auf den Screenshots zusehen, startet Bibbot nicht mal die Suche.

![chrome_ohnvrHxMKu](https://github.com/stefanw/bibbot/assets/32475477/ce8d3a5c-363c-435a-b9ae-cafc2183b941)
![chrome_6gtq8aSnH3](https://github.com/stefanw/bibbot/assets/32475477/7b044a38-6256-46f9-bb51-d182f7d5459b)

**Vielen Dank** für das Projekt, hoffentlich lässt es sich einfach / schnell fixen mit der Seite der Berliner Morgenpost.

**Comment by range** [comment]
Ich sehe das gleiche Problem bei dem oben genannten Artikel, aber auch beim Beispielartikel, den die Bibbot-Extension bei der Zeit öffnet - hier wird ebenfalls keine Suche bei der Voebb angestoßen. 

<img width="551" alt="image" src="https://github.com/stefanw/bibbot/assets/346905/3937f587-49f2-4e6e-a0d2-ff4971c2c1b3">

Browser ist Firefox 121.0.1 auf MacOS 14.1.2
