### ISSUE TITLE
Hamburger Abendblatt funktioniert nicht mehr nach Relaunch

### ISSUE THREAD

**Issue by SilkeBritz** [stefanw/bibbot#428]
Beispiel: 

https://www.abendblatt.de/hamburg/kultur/article241512236/Mit-radikalen-Rechten-reden-Das-ist-voellig-sinnlos.html

https://buecherhallen.genios.de/document/HA__d730e0dfa1fa357ccd71a45d580ec1106b90f906

Quelle: | Hamburger Abendblatt - Hamburg vom 27.01.2024 Seite 23
-- | --
Ressort: | Kultur
Ausgabe: | Hamburg
Dokumentnummer: | 7A5829112F0B1818B493360E3C2F25B7_5507165

**Comment by stefanw** [comment]
Latest version 0.35.0 fixes abendblatt.de. However, this specific article cannot be found due to differences in wording between online article and database.

**Comment by SilkeBritz** [comment]
Versino 0.35 
- Chrome: (noch?) nicht für Chrome verfügbar
- Safari: Bücherei lässt sich nicht auswählen, Zugangsdaten lassen sich nicht eingeben
- Firefox: funktioniert

**Comment by stefanw** [comment]
0.35 for chrome is available. If you another issue with Safari, please open a new issue.
