### ISSUE TITLE
[Nachrichtenseite]: Badische Zeitung

### ISSUE THREAD

**Issue by IVI-I** [stefanw/bibbot#430]
### URL der Nachrichtenseite

https://www.badische-zeitung.de

### URL zu einem Artikel mit Paywall

https://www.badische-zeitung.de/40-jahre-fasnachtspraesident-die-fasnacht-schwingt-immer-mit-auch-nach-dem-abschied

### Ist die Nachrichtenseite in einer Pressedatenbank enthalten?

Genios

### URL zu der Quellenseite in der Pressedatenbank

https://www.genios.de/presse-archiv/quelle/BADZ/0/1/badische-zeitung.html

### Weitere Details

https://www.genios.de/presse-archiv/quelle/BADZ/0/1/badische-zeitung.html
or
https://www.genios.de/browse/Alle/Presse/Presse%20Deutschland/Badische%20Zeitung

**Comment by florisre** [comment]
Badische Zeitung hat zeitweise funktioniert, neuerdings wird aber keine Suche in der Datenbank mehr angestoßen. Ich vermute das liegt an Änderungen seitens der Badischen Zeitung?

**Comment by florisre** [comment]
Ich vermute, dass das an folgender Veränderung liegt:

in [sites.ts](https://github.com/stefanw/bibbot/blob/main/src/sites.ts) ist momentan die Auswahl des Elementes `.freemium__preview` angegeben, dieses scheint jetzt ´artikelPreview` zu heißen.

Hier der HTML-Quelltext einer Beispielseite:

```
<section class="artikelPreview article-site-plr | ff-accent | mb-1000" role="article" data-bottalk="no">
						

			
			<!-- RSPEAK_START -->
						
								Um rund ein Drittel ist die Zahl der beim Landratsamt gestellten Bauanträge in den ersten vier Monaten des Jahres gegenüber dem Vergleichszeitraum 2023 gesunken. Eine Zahl, die Landrat Hanno Hurth bei seinen Grußworten zum Maibaumstellen der Kreishandwerkerschaft verlautbarte. Dabei wies er darauf hin, dass gerade das hiesige Bauhandwerk von den damit verbundenen ...
			<!-- RSPEAK_STOP -->
		</section>
```
