### ISSUE TITLE
Safari version doesn't work reliable

### ISSUE THREAD

**Issue by 343max** [stefanw/bibbot#438]
Because the Safari app doesn't seem to be properly signed I need to allow unsigned extensions in the Safari Developer Settings and then enable the bibbot extension and then login again every time I restart Safari, which makes the extension bearly usable in Safari.

I can offer my help to setup the deployment process and while on it I could also help bringing the extension to Safari for iOS.

**Comment by stefanw** [comment]
My understanding is that you can only sign the extension via the App Store but BibBot has been rejected by the App Store. Is that correct?

**Comment by 343max** [comment]
I see. I wasn't aware the extension got rejected. *sigh*
