### ISSUE TITLE
https://bib-nuernberg.genios.de keine Suche nach Artikel

### ISSUE THREAD

**Issue by Stonewall6165** [stefanw/bibbot#443]
Hallo,

die Seite geht auf, er sucht jedoch nicht, sondern ich lande auf der Suchseite.  Ich muss mich auch von Hand einmal einloggen. Auch nach einem neuladen der Seite mit dem Artikel, geht nur die Suchseite auf.

BibBot v0.35.0

**Comment by SoftwareRat** [comment]
Ich habe dasselbe Problem mit derselben Seite, ein temporäre Problemlösung wäre den Browser neu zu starten, ist aber sehr nervig auf Dauer.

**Comment by CaptainReginaldBull** [comment]
Habe das gleich Problem. Die BIB Nürnberg nutzt mittlerweile eine neuere GENIOS Oberfläche. Automatische Suchen funktionieren nicht mehr. Es wird nur die GENIOS Seite der BIB Nürnberg geöffnet. Keine Abhilfe durch Browserneustart. 

bibbot: v0.36.0
Firefox: 124.0.1
Win: 10

**Comment by Stonewall6165** [comment]
Gibt inzwischen einen neuen Fehler:
![image](https://github.com/stefanw/bibbot/assets/10817183/62d52564-a2a7-4f33-997f-0c31a6b268b9)
