### ISSUE TITLE
Tagesspiegel nicht mehr abrufbar

### ISSUE THREAD

**Issue by fmlo** [stefanw/bibbot#455]
Leider wird der Bot bei Artikeln des Tagesspiegel nicht mehr aktiv. Das Tab mit der Weiterleitung zum Genios-Login öffnet sich nicht (Firefox, Windows). Gibt es eine Einstellung, an der ich drehen kann, oder eine Lösung mittels Update?

**Comment by georgkrause** [comment]
Ich habe das gleiche Problem, kann ich irgendwie beim debuggen helfen?
