### ISSUE TITLE
[Bibliothek]: Stadtbibliothek Ludwigsburg

### ISSUE THREAD

**Issue by Annette-Krause** [stefanw/bibbot#469]
### Name der Bibliothek

Stadtbibliothek Ludwigsburg

### Webseite der Bibliothek

https://stabi.ludwigsburg.de/start

### Angebotene Pressedatenbank

Genios

### URL zur Pressedatenbank

https://www.pressreader.com/de

### Weitere Details

Jetzt bin ich verwirrt. Vermutlich macht es keinen Sinn, die Stadtbibliothek Ludwigsburg aufzunehmen, da sie Pressreader lizenziert haben.

mit freundlichem Gruß
Annette Krause
dfi

**Comment by stefanw** [comment]
Keine Pressedatenbank.
