### ISSUE TITLE
SZ startet nicht ( Url: https://www.sueddeutsche.de/politik/verkehr-fdp-autofahrer-radwege-lux.TiMTRHGT4Rog4QL9nnrk3?reduced=true )

### ISSUE THREAD

**Issue by Wikinaut** [stefanw/bibbot#482]
Url: https://www.sueddeutsche.de/politik/verkehr-fdp-autofahrer-radwege-lux.TiMTRHGT4Rog4QL9nnrk3?reduced=true triggert leider den BibBot nicht.

**Comment by stefanw** [comment]
Kann ich mit der aktuellen Version v0.37.0 nicht nachvollziehen.

**Comment by Wikinaut** [comment]
Hi.

Obwohl ich auf meinen Firefox-Installationen (mehrere) automatische Updates eingeschaltet habe, habe ich offenbar ältere Version(en), beispielsweise:

![grafik](https://github.com/user-attachments/assets/bfd967d2-73b3-4956-8149-e6046fd8e0fb)

**Comment by Wikinaut** [comment]
Firefox "Auf Updates prüfen": ø Updates verfügbar

**Comment by Wikinaut** [comment]
Ich habe bibbot jetzt de- und neu installiert.

**Comment by Wikinaut** [comment]
Und, wie verhext, voebb wird gerade gewartet.......

**Comment by Wikinaut** [comment]
(works for me) (version 0.37.0)
