### ISSUE TITLE
Voebb mit Genius scheint nicht mehr zu funktionieren

### ISSUE THREAD

**Issue by jfilter** [stefanw/bibbot#486]
Bekommen z. B. bei dem Testartikel das hier angezeigt. macOS, Firefox, v0.37.0

<img width="1387" alt="Screenshot 2024-09-03 at 15 43 02" src="https://github.com/user-attachments/assets/da37b0c9-9e76-4f05-9013-1808393abbe8">

**Comment by zckman** [comment]
Wurde schon korrigiert: https://github.com/stefanw/bibbot/commit/a641c3bff110c0435c94ef7d8e9d40eec6ed0e47

**Comment by jfilter** [comment]
Danke @zckman. Dann warte ich mal auf das Update.

**Comment by stefanw** [comment]
Automatic release leider offenbar kaputt, aber 0.38.0 gibt‘s schon auf der GitHub release Seite.

**Comment by stefanw** [comment]
v0.38.1 ist jetzt für Firefox als normales Update verfügbar. Chrome hängt wegen einer neuen Permission noch in der review.
