### ISSUE TITLE
Welt.de doppelte Aboabfrage

### ISSUE THREAD

**Issue by juliankpf** [stefanw/bibbot#7]
auf der welt.de Seite sind die Artikel anscheinend doppelt "gesichert".

Beispiel: https://www.welt.de/kultur/plus228038357/Generation-Warnhinweis-Vom-Explicit-Content-zu-Disney.html

siehe: https://img.salty.cloud/LqN9AmBiXF.gif (Video!)

**Comment by stefanw** [comment]
Der gesamte Artikel ist mit VÖBBot lesbar. Was da am Ende der Seite noch unter der Paywall ist, ist fake und tut nur so als wäre es der Inhalt, um Leute zum Abo-Abschluss zu animieren ("Ich sehe den Artikel ja fast, so nah dran!!").

Hier muss die Paywall-Entfernung angepasst werden, damit dieser Unsinn auch noch verschwindet.
